from PyQt5.QtWidgets import *
from PyQt5 import QtCore

from ui_teachers import Ui_TeachersWindow

class ControllerTeachers(QWidget, Ui_TeachersWindow):
    """教师控制类"""
    signal_ui_choose = QtCore.pyqtSignal(str)
    signal_teacher_choose = QtCore.pyqtSignal(str)

    def __init__(self):
        """初始化登录控制类"""
        super(ControllerTeachers, self).__init__()
        self.setupUi(self)
        self.teacherIndex = 0  # 选择的教师的索引号
        # 连接界面返回信号与槽
        self.pushButton_back.clicked.connect(self.on_back)
        # 连接教师选择的信号与槽
        self.pushButton_teacher_1.clicked.connect(lambda: self.signal_teacher_choose.emit("曾攀"))
        self.pushButton_teacher_2.clicked.connect(lambda: self.signal_teacher_choose.emit("曾绍华"))
        self.pushButton_teacher_3.clicked.connect(lambda: self.signal_teacher_choose.emit("曾智"))
        self.pushButton_teacher_4.clicked.connect(lambda: self.signal_teacher_choose.emit("陈代江"))
        self.pushButton_teacher_5.clicked.connect(lambda: self.signal_teacher_choose.emit("陈娟娟"))
        self.pushButton_teacher_6.clicked.connect(lambda: self.signal_teacher_choose.emit("陈兰"))
        self.pushButton_teacher_7.clicked.connect(lambda: self.signal_teacher_choose.emit("陈勇"))
        self.pushButton_teacher_8.clicked.connect(lambda: self.signal_teacher_choose.emit("丛鑫"))
        self.pushButton_teacher_9.clicked.connect(lambda: self.signal_teacher_choose.emit("崔少国"))
        self.pushButton_teacher_10.clicked.connect(lambda: self.signal_teacher_choose.emit("邓毅"))
        self.pushButton_teacher_11.clicked.connect(lambda: self.signal_teacher_choose.emit("翟浩"))
        self.pushButton_teacher_12.clicked.connect(lambda: self.signal_teacher_choose.emit("杜兴"))
        self.pushButton_teacher_13.clicked.connect(lambda: self.signal_teacher_choose.emit("范京春"))
        self.pushButton_teacher_14.clicked.connect(lambda: self.signal_teacher_choose.emit("范永胜"))
        self.pushButton_teacher_15.clicked.connect(lambda: self.signal_teacher_choose.emit("冯骥"))
        self.pushButton_teacher_16.clicked.connect(lambda: self.signal_teacher_choose.emit("傅帆"))
        self.pushButton_teacher_17.clicked.connect(lambda: self.signal_teacher_choose.emit("龚伟"))
        self.pushButton_teacher_18.clicked.connect(lambda: self.signal_teacher_choose.emit("郝占章"))
        self.pushButton_teacher_19.clicked.connect(lambda: self.signal_teacher_choose.emit("何东"))
        self.pushButton_teacher_20.clicked.connect(lambda: self.signal_teacher_choose.emit("何丽"))
        self.pushButton_teacher_21.clicked.connect(lambda: self.signal_teacher_choose.emit("江军"))
        self.pushButton_teacher_22.clicked.connect(lambda: self.signal_teacher_choose.emit("姜扬"))
        self.pushButton_teacher_23.clicked.connect(lambda: self.signal_teacher_choose.emit("蒋明宇"))
        self.pushButton_teacher_24.clicked.connect(lambda: self.signal_teacher_choose.emit("靳蜜静"))
        self.pushButton_teacher_25.clicked.connect(lambda: self.signal_teacher_choose.emit("赖莉"))
        self.pushButton_teacher_26.clicked.connect(lambda: self.signal_teacher_choose.emit("兰晓红"))
        self.pushButton_teacher_27.clicked.connect(lambda: self.signal_teacher_choose.emit("雷蕾"))
        self.pushButton_teacher_28.clicked.connect(lambda: self.signal_teacher_choose.emit("黎天送"))
        self.pushButton_teacher_29.clicked.connect(lambda: self.signal_teacher_choose.emit("李光菊"))
        self.pushButton_teacher_30.clicked.connect(lambda: self.signal_teacher_choose.emit("李明"))
        self.pushButton_teacher_31.clicked.connect(lambda: self.signal_teacher_choose.emit("李明勇"))
        self.pushButton_teacher_32.clicked.connect(lambda: self.signal_teacher_choose.emit("李世宏"))
        self.pushButton_teacher_33.clicked.connect(lambda: self.signal_teacher_choose.emit("李晓虹"))
        self.pushButton_teacher_34.clicked.connect(lambda: self.signal_teacher_choose.emit("刘宇"))
        self.pushButton_teacher_35.clicked.connect(lambda: self.signal_teacher_choose.emit("楼英浩"))
        self.pushButton_teacher_36.clicked.connect(lambda: self.signal_teacher_choose.emit("罗凌"))
        self.pushButton_teacher_37.clicked.connect(lambda: self.signal_teacher_choose.emit("罗世祥"))
        self.pushButton_teacher_38.clicked.connect(lambda: self.signal_teacher_choose.emit("吕佳"))
        self.pushButton_teacher_39.clicked.connect(lambda: self.signal_teacher_choose.emit("马燕"))
        self.pushButton_teacher_40.clicked.connect(lambda: self.signal_teacher_choose.emit("牟小红"))
        self.pushButton_teacher_41.clicked.connect(lambda: self.signal_teacher_choose.emit("牟颖"))
        self.pushButton_teacher_42.clicked.connect(lambda: self.signal_teacher_choose.emit("牛彦敏"))
        self.pushButton_teacher_43.clicked.connect(lambda: self.signal_teacher_choose.emit("彭静"))
        self.pushButton_teacher_44.clicked.connect(lambda: self.signal_teacher_choose.emit("彭顺顺"))
        self.pushButton_teacher_45.clicked.connect(lambda: self.signal_teacher_choose.emit("冉瑞生"))
        self.pushButton_teacher_46.clicked.connect(lambda: self.signal_teacher_choose.emit("沙轩"))
        self.pushButton_teacher_47.clicked.connect(lambda: self.signal_teacher_choose.emit("尚晋"))
        self.pushButton_teacher_48.clicked.connect(lambda: self.signal_teacher_choose.emit("宋婷婷"))
        self.pushButton_teacher_49.clicked.connect(lambda: self.signal_teacher_choose.emit("孙苗"))
        self.pushButton_teacher_50.clicked.connect(lambda: self.signal_teacher_choose.emit("孙平"))
        self.pushButton_teacher_51.clicked.connect(lambda: self.signal_teacher_choose.emit("谭华山"))
        self.pushButton_teacher_52.clicked.connect(lambda: self.signal_teacher_choose.emit("唐万梅"))
        self.pushButton_teacher_53.clicked.connect(lambda: self.signal_teacher_choose.emit("汪平"))
        self.pushButton_teacher_54.clicked.connect(lambda: self.signal_teacher_choose.emit("王艳霞"))
        self.pushButton_teacher_55.clicked.connect(lambda: self.signal_teacher_choose.emit("魏延"))
        self.pushButton_teacher_56.clicked.connect(lambda: self.signal_teacher_choose.emit("文向波"))
        self.pushButton_teacher_57.clicked.connect(lambda: self.signal_teacher_choose.emit("先强"))
        self.pushButton_teacher_58.clicked.connect(lambda: self.signal_teacher_choose.emit("肖颗"))
        self.pushButton_teacher_59.clicked.connect(lambda: self.signal_teacher_choose.emit("徐传运"))
        self.pushButton_teacher_60.clicked.connect(lambda: self.signal_teacher_choose.emit("杨丹"))
        self.pushButton_teacher_61.clicked.connect(lambda: self.signal_teacher_choose.emit("杨德刚"))
        self.pushButton_teacher_62.clicked.connect(lambda: self.signal_teacher_choose.emit("杨卫明"))
        self.pushButton_teacher_63.clicked.connect(lambda: self.signal_teacher_choose.emit("叶青"))
        self.pushButton_teacher_64.clicked.connect(lambda: self.signal_teacher_choose.emit("游中胜"))
        self.pushButton_teacher_65.clicked.connect(lambda: self.signal_teacher_choose.emit("余磊"))
        self.pushButton_teacher_66.clicked.connect(lambda: self.signal_teacher_choose.emit("余萍"))
        self.pushButton_teacher_67.clicked.connect(lambda: self.signal_teacher_choose.emit("詹志飞"))
        self.pushButton_teacher_68.clicked.connect(lambda: self.signal_teacher_choose.emit("张高亮"))
        self.pushButton_teacher_69.clicked.connect(lambda: self.signal_teacher_choose.emit("张万里"))
        self.pushButton_teacher_70.clicked.connect(lambda: self.signal_teacher_choose.emit("张文峰"))
        self.pushButton_teacher_71.clicked.connect(lambda: self.signal_teacher_choose.emit("张杨"))
        self.pushButton_teacher_72.clicked.connect(lambda: self.signal_teacher_choose.emit("张珍瑜"))
        self.pushButton_teacher_73.clicked.connect(lambda: self.signal_teacher_choose.emit("郑玉春"))
        self.pushButton_teacher_74.clicked.connect(lambda: self.signal_teacher_choose.emit("钟华"))
        self.pushButton_teacher_75.clicked.connect(lambda: self.signal_teacher_choose.emit("周春丽"))
        self.pushButton_teacher_76.clicked.connect(lambda: self.signal_teacher_choose.emit("周杨"))
        self.pushButton_teacher_77.clicked.connect(lambda: self.signal_teacher_choose.emit("朱德利"))
        self.pushButton_teacher_78.clicked.connect(lambda: self.signal_teacher_choose.emit("訾玲玲"))

        self.pushButton_teacher_1.clicked.connect(lambda: self.signal_ui_choose.emit("teacherInfo"))
        self.pushButton_teacher_2.clicked.connect(lambda: self.signal_ui_choose.emit("teacherInfo"))
        self.pushButton_teacher_3.clicked.connect(lambda: self.signal_ui_choose.emit("teacherInfo"))
        self.pushButton_teacher_4.clicked.connect(lambda: self.signal_ui_choose.emit("teacherInfo"))
        self.pushButton_teacher_5.clicked.connect(lambda: self.signal_ui_choose.emit("teacherInfo"))
        self.pushButton_teacher_6.clicked.connect(lambda: self.signal_ui_choose.emit("teacherInfo"))
        self.pushButton_teacher_7.clicked.connect(lambda: self.signal_ui_choose.emit("teacherInfo"))
        self.pushButton_teacher_8.clicked.connect(lambda: self.signal_ui_choose.emit("teacherInfo"))
        self.pushButton_teacher_9.clicked.connect(lambda: self.signal_ui_choose.emit("teacherInfo"))
        self.pushButton_teacher_10.clicked.connect(lambda: self.signal_ui_choose.emit("teacherInfo"))
        self.pushButton_teacher_11.clicked.connect(lambda: self.signal_ui_choose.emit("teacherInfo"))
        self.pushButton_teacher_12.clicked.connect(lambda: self.signal_ui_choose.emit("teacherInfo"))
        self.pushButton_teacher_13.clicked.connect(lambda: self.signal_ui_choose.emit("teacherInfo"))
        self.pushButton_teacher_14.clicked.connect(lambda: self.signal_ui_choose.emit("teacherInfo"))
        self.pushButton_teacher_15.clicked.connect(lambda: self.signal_ui_choose.emit("teacherInfo"))
        self.pushButton_teacher_16.clicked.connect(lambda: self.signal_ui_choose.emit("teacherInfo"))
        self.pushButton_teacher_17.clicked.connect(lambda: self.signal_ui_choose.emit("teacherInfo"))
        self.pushButton_teacher_18.clicked.connect(lambda: self.signal_ui_choose.emit("teacherInfo"))
        self.pushButton_teacher_19.clicked.connect(lambda: self.signal_ui_choose.emit("teacherInfo"))
        self.pushButton_teacher_20.clicked.connect(lambda: self.signal_ui_choose.emit("teacherInfo"))
        self.pushButton_teacher_21.clicked.connect(lambda: self.signal_ui_choose.emit("teacherInfo"))
        self.pushButton_teacher_22.clicked.connect(lambda: self.signal_ui_choose.emit("teacherInfo"))
        self.pushButton_teacher_23.clicked.connect(lambda: self.signal_ui_choose.emit("teacherInfo"))
        self.pushButton_teacher_24.clicked.connect(lambda: self.signal_ui_choose.emit("teacherInfo"))
        self.pushButton_teacher_25.clicked.connect(lambda: self.signal_ui_choose.emit("teacherInfo"))
        self.pushButton_teacher_26.clicked.connect(lambda: self.signal_ui_choose.emit("teacherInfo"))
        self.pushButton_teacher_27.clicked.connect(lambda: self.signal_ui_choose.emit("teacherInfo"))
        self.pushButton_teacher_28.clicked.connect(lambda: self.signal_ui_choose.emit("teacherInfo"))
        self.pushButton_teacher_29.clicked.connect(lambda: self.signal_ui_choose.emit("teacherInfo"))
        self.pushButton_teacher_30.clicked.connect(lambda: self.signal_ui_choose.emit("teacherInfo"))
        self.pushButton_teacher_31.clicked.connect(lambda: self.signal_ui_choose.emit("teacherInfo"))
        self.pushButton_teacher_32.clicked.connect(lambda: self.signal_ui_choose.emit("teacherInfo"))
        self.pushButton_teacher_33.clicked.connect(lambda: self.signal_ui_choose.emit("teacherInfo"))
        self.pushButton_teacher_34.clicked.connect(lambda: self.signal_ui_choose.emit("teacherInfo"))
        self.pushButton_teacher_35.clicked.connect(lambda: self.signal_ui_choose.emit("teacherInfo"))
        self.pushButton_teacher_36.clicked.connect(lambda: self.signal_ui_choose.emit("teacherInfo"))
        self.pushButton_teacher_37.clicked.connect(lambda: self.signal_ui_choose.emit("teacherInfo"))
        self.pushButton_teacher_38.clicked.connect(lambda: self.signal_ui_choose.emit("teacherInfo"))
        self.pushButton_teacher_39.clicked.connect(lambda: self.signal_ui_choose.emit("teacherInfo"))
        self.pushButton_teacher_40.clicked.connect(lambda: self.signal_ui_choose.emit("teacherInfo"))
        self.pushButton_teacher_41.clicked.connect(lambda: self.signal_ui_choose.emit("teacherInfo"))
        self.pushButton_teacher_42.clicked.connect(lambda: self.signal_ui_choose.emit("teacherInfo"))
        self.pushButton_teacher_43.clicked.connect(lambda: self.signal_ui_choose.emit("teacherInfo"))
        self.pushButton_teacher_44.clicked.connect(lambda: self.signal_ui_choose.emit("teacherInfo"))
        self.pushButton_teacher_45.clicked.connect(lambda: self.signal_ui_choose.emit("teacherInfo"))
        self.pushButton_teacher_46.clicked.connect(lambda: self.signal_ui_choose.emit("teacherInfo"))
        self.pushButton_teacher_47.clicked.connect(lambda: self.signal_ui_choose.emit("teacherInfo"))
        self.pushButton_teacher_48.clicked.connect(lambda: self.signal_ui_choose.emit("teacherInfo"))
        self.pushButton_teacher_49.clicked.connect(lambda: self.signal_ui_choose.emit("teacherInfo"))
        self.pushButton_teacher_50.clicked.connect(lambda: self.signal_ui_choose.emit("teacherInfo"))
        self.pushButton_teacher_51.clicked.connect(lambda: self.signal_ui_choose.emit("teacherInfo"))
        self.pushButton_teacher_52.clicked.connect(lambda: self.signal_ui_choose.emit("teacherInfo"))
        self.pushButton_teacher_53.clicked.connect(lambda: self.signal_ui_choose.emit("teacherInfo"))
        self.pushButton_teacher_54.clicked.connect(lambda: self.signal_ui_choose.emit("teacherInfo"))
        self.pushButton_teacher_55.clicked.connect(lambda: self.signal_ui_choose.emit("teacherInfo"))
        self.pushButton_teacher_56.clicked.connect(lambda: self.signal_ui_choose.emit("teacherInfo"))
        self.pushButton_teacher_57.clicked.connect(lambda: self.signal_ui_choose.emit("teacherInfo"))
        self.pushButton_teacher_58.clicked.connect(lambda: self.signal_ui_choose.emit("teacherInfo"))
        self.pushButton_teacher_59.clicked.connect(lambda: self.signal_ui_choose.emit("teacherInfo"))
        self.pushButton_teacher_60.clicked.connect(lambda: self.signal_ui_choose.emit("teacherInfo"))
        self.pushButton_teacher_61.clicked.connect(lambda: self.signal_ui_choose.emit("teacherInfo"))
        self.pushButton_teacher_62.clicked.connect(lambda: self.signal_ui_choose.emit("teacherInfo"))
        self.pushButton_teacher_63.clicked.connect(lambda: self.signal_ui_choose.emit("teacherInfo"))
        self.pushButton_teacher_64.clicked.connect(lambda: self.signal_ui_choose.emit("teacherInfo"))
        self.pushButton_teacher_65.clicked.connect(lambda: self.signal_ui_choose.emit("teacherInfo"))
        self.pushButton_teacher_66.clicked.connect(lambda: self.signal_ui_choose.emit("teacherInfo"))
        self.pushButton_teacher_67.clicked.connect(lambda: self.signal_ui_choose.emit("teacherInfo"))
        self.pushButton_teacher_68.clicked.connect(lambda: self.signal_ui_choose.emit("teacherInfo"))
        self.pushButton_teacher_69.clicked.connect(lambda: self.signal_ui_choose.emit("teacherInfo"))
        self.pushButton_teacher_70.clicked.connect(lambda: self.signal_ui_choose.emit("teacherInfo"))
        self.pushButton_teacher_71.clicked.connect(lambda: self.signal_ui_choose.emit("teacherInfo"))
        self.pushButton_teacher_72.clicked.connect(lambda: self.signal_ui_choose.emit("teacherInfo"))
        self.pushButton_teacher_73.clicked.connect(lambda: self.signal_ui_choose.emit("teacherInfo"))
        self.pushButton_teacher_74.clicked.connect(lambda: self.signal_ui_choose.emit("teacherInfo"))
        self.pushButton_teacher_75.clicked.connect(lambda: self.signal_ui_choose.emit("teacherInfo"))
        self.pushButton_teacher_76.clicked.connect(lambda: self.signal_ui_choose.emit("teacherInfo"))
        self.pushButton_teacher_77.clicked.connect(lambda: self.signal_ui_choose.emit("teacherInfo"))
        self.pushButton_teacher_78.clicked.connect(lambda: self.signal_ui_choose.emit("teacherInfo"))

    def on_back(self):
        """返回到home界面的槽"""
        self.signal_ui_choose.emit("home")




