# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_home.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import *
from PyQt5.QtGui import QMovie

class Ui_HomeWindow(object):
    def setupUi(self, HomeWindow):
        HomeWindow.setObjectName("HomeWindow")
        HomeWindow.resize(480, 800)
        HomeWindow.setMinimumSize(QtCore.QSize(480, 800))
        HomeWindow.setMaximumSize(QtCore.QSize(480, 800))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Icon/Images/Icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        HomeWindow.setWindowIcon(icon)
        HomeWindow.setStyleSheet("color: rgb(200, 200, 200);\n"
"background-color: rgb(47, 79, 79);")
        self.frame_function = QtWidgets.QFrame(HomeWindow)
        self.frame_function.setGeometry(QtCore.QRect(0, 250, 80, 450))
        self.frame_function.setMinimumSize(QtCore.QSize(80, 450))
        self.frame_function.setMaximumSize(QtCore.QSize(80, 450))
        self.frame_function.setStyleSheet("background:rgb(51,51,51);")
        self.frame_function.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_function.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_function.setObjectName("frame_function")
        self.frame_use = QtWidgets.QFrame(self.frame_function)
        self.frame_use.setGeometry(QtCore.QRect(0, 0, 80, 55))
        self.frame_use.setMinimumSize(QtCore.QSize(80, 55))
        self.frame_use.setMaximumSize(QtCore.QSize(80, 55))
        self.frame_use.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_use.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_use.setObjectName("frame_use")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.frame_use)
        self.horizontalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_16.setSpacing(0)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.pushButton_use = QtWidgets.QPushButton(self.frame_use)
        self.pushButton_use.setMinimumSize(QtCore.QSize(80, 55))
        self.pushButton_use.setMaximumSize(QtCore.QSize(80, 55))
        self.pushButton_use.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    background-color: rgba(0,0,0,0);\n"
"}\n"
"QPushButton:hover {\n"
"\n"
"    background-color: rgb(0,143,150);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgba(0,0,0,0);\n"
"}")
        self.pushButton_use.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/home/Images/use.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_use.setIcon(icon1)
        self.pushButton_use.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_use.setFlat(True)
        self.pushButton_use.setObjectName("pushButton_use")
        self.horizontalLayout_16.addWidget(self.pushButton_use)
        self.frame_view = QtWidgets.QFrame(self.frame_function)
        self.frame_view.setGeometry(QtCore.QRect(0, 60, 80, 55))
        self.frame_view.setMinimumSize(QtCore.QSize(80, 55))
        self.frame_view.setMaximumSize(QtCore.QSize(80, 55))
        self.frame_view.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_view.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_view.setObjectName("frame_view")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.frame_view)
        self.horizontalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_17.setSpacing(0)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.pushButton_view = QtWidgets.QPushButton(self.frame_view)
        self.pushButton_view.setMinimumSize(QtCore.QSize(80, 55))
        self.pushButton_view.setMaximumSize(QtCore.QSize(80, 55))
        self.pushButton_view.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    background-color: rgba(0,0,0,0);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(0,143,150);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgba(0,0,0,0);\n"
"}")
        self.pushButton_view.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/home/Images/view.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_view.setIcon(icon2)
        self.pushButton_view.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_view.setFlat(True)
        self.pushButton_view.setObjectName("pushButton_view")
        self.horizontalLayout_17.addWidget(self.pushButton_view)
        self.frame_about = QtWidgets.QFrame(self.frame_function)
        self.frame_about.setGeometry(QtCore.QRect(0, 120, 80, 55))
        self.frame_about.setMinimumSize(QtCore.QSize(80, 55))
        self.frame_about.setMaximumSize(QtCore.QSize(80, 55))
        self.frame_about.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_about.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_about.setObjectName("frame_about")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.frame_about)
        self.horizontalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_18.setSpacing(0)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.pushButton_about = QtWidgets.QPushButton(self.frame_about)
        self.pushButton_about.setMinimumSize(QtCore.QSize(80, 55))
        self.pushButton_about.setMaximumSize(QtCore.QSize(80, 55))
        self.pushButton_about.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    background-color: rgba(0,0,0,0);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(0,143,150);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgba(0,0,0,0);\n"
"}")
        self.pushButton_about.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/home/Images/about.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_about.setIcon(icon3)
        self.pushButton_about.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_about.setFlat(True)
        self.pushButton_about.setObjectName("pushButton_about")
        self.horizontalLayout_18.addWidget(self.pushButton_about)
        self.label_top = QtWidgets.QLabel(HomeWindow)
        self.label_top.setGeometry(QtCore.QRect(0, 0, 480, 250))
        self.label_top.setText("")
        self.label_top.setObjectName("label_top")
        self.pushButton_reserve = QtWidgets.QPushButton(HomeWindow)
        self.pushButton_reserve.setGeometry(QtCore.QRect(80, 250, 400, 150))
        self.pushButton_reserve.setMinimumSize(QtCore.QSize(400, 150))
        self.pushButton_reserve.setMaximumSize(QtCore.QSize(400, 150))
        self.pushButton_reserve.setStyleSheet("QPushButton {\n"
"    background-image: url(:/home/Images/reserve.png);\n"
"    background-position: center;\n"
"    border-radius: 60px;\n"
"    border: 10px solid rgb(205, 16, 118);\n"
"}\n"
"QPushButton:hover {\n"
"    border: 10px solid rgb(255, 255, 0);\n"
"}")
        self.pushButton_reserve.setText("")
        self.pushButton_reserve.setObjectName("pushButton_reserve")
        self.label_bottom = QtWidgets.QLabel(HomeWindow)
        self.label_bottom.setGeometry(QtCore.QRect(0, 700, 480, 100))
        self.label_bottom.setMinimumSize(QtCore.QSize(480, 100))
        self.label_bottom.setMaximumSize(QtCore.QSize(480, 100))
        self.label_bottom.setStyleSheet("")
        self.label_bottom.setText("")
        self.label_bottom.setObjectName("label_bottom")
        self.pushButton_web = QtWidgets.QPushButton(HomeWindow)
        self.pushButton_web.setGeometry(QtCore.QRect(80, 400, 400, 150))
        self.pushButton_web.setMinimumSize(QtCore.QSize(400, 150))
        self.pushButton_web.setMaximumSize(QtCore.QSize(400, 150))
        self.pushButton_web.setStyleSheet("QPushButton {\n"
"    background-image: url(:/home/Images/web.png);\n"
"    background-position: center;\n"
"    border-radius: 60px;\n"
"    border: 10px solid rgb(205, 16, 118);\n"
"}\n"
"QPushButton:hover {\n"
"    border: 10px solid rgb(255, 255, 0);\n"
"}")
        self.pushButton_web.setText("")
        self.pushButton_web.setObjectName("pushButton_web")
        self.pushButton_teacher = QtWidgets.QPushButton(HomeWindow)
        self.pushButton_teacher.setGeometry(QtCore.QRect(80, 550, 400, 150))
        self.pushButton_teacher.setMinimumSize(QtCore.QSize(400, 150))
        self.pushButton_teacher.setMaximumSize(QtCore.QSize(400, 150))
        self.pushButton_teacher.setStyleSheet("QPushButton {\n"
"    background-image: url(:/home/Images/teacher.png);\n"
"    background-position: center;\n"
"    border-radius: 60px;\n"
"    border: 10px solid rgb(205, 16, 118);\n"
"}\n"
"QPushButton:hover {\n"
"    border: 10px solid rgb(255, 255, 0);\n"
"}")
        self.pushButton_teacher.setText("")
        self.pushButton_teacher.setObjectName("pushButton_teacher")

        """启动gif"""
        self.gif1 = QMovie('./Images/cover.gif')
        self.label_top.setMovie(self.gif1)
        self.gif1.start()
        self.gif2 = QMovie('./Images/bottom.gif')
        self.label_bottom.setMovie(self.gif2)
        self.gif2.start()

        self.retranslateUi(HomeWindow)
        QtCore.QMetaObject.connectSlotsByName(HomeWindow)

    def retranslateUi(self, HomeWindow):
        _translate = QtCore.QCoreApplication.translate
        HomeWindow.setWindowTitle(_translate("HomeWindow", "cqnu_spider"))
        self.pushButton_use.setToolTip(_translate("HomeWindow", "功能介绍"))
        self.pushButton_view.setToolTip(_translate("HomeWindow", "梦厅规则"))
        self.pushButton_about.setToolTip(_translate("HomeWindow", "关于软件"))
import ui_rc

if __name__ == "__main__":
    import sys
    app = QApplication(sys.argv)
    ui = Ui_HomeWindow()
    window = QWidget()
    ui.setupUi(window)
    window.show()
    sys.exit(app.exec_())