# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_teacher_info.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TeacherInfoWindow(object):
    def setupUi(self, TeacherInfoWindow):
        TeacherInfoWindow.setObjectName("TeacherInfoWindow")
        TeacherInfoWindow.resize(480, 800)
        TeacherInfoWindow.setMinimumSize(QtCore.QSize(480, 800))
        TeacherInfoWindow.setMaximumSize(QtCore.QSize(480, 800))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Icon/Images/Icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        TeacherInfoWindow.setWindowIcon(icon)
        TeacherInfoWindow.setStyleSheet("color: rgb(200, 200, 200);\n"
"background-color: rgb(47, 79, 79);")
        self.frame_top = QtWidgets.QFrame(TeacherInfoWindow)
        self.frame_top.setGeometry(QtCore.QRect(0, 0, 480, 50))
        self.frame_top.setStyleSheet("background: rgb(205, 104, 57)")
        self.frame_top.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_top.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_top.setObjectName("frame_top")
        self.pushButton_back = QtWidgets.QPushButton(self.frame_top)
        self.pushButton_back.setGeometry(QtCore.QRect(430, 0, 50, 50))
        self.pushButton_back.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButton_back.setMaximumSize(QtCore.QSize(50, 50))
        self.pushButton_back.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    background-color: rgba(0,0,0,0);\n"
"    background: url(:/ui_back/Images/ui_back.png)\n"
"}\n"
"QPushButton:hover {\n"
"\n"
"    background-color: rgb(0,143,150);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgba(0,0,0,0);\n"
"}")
        self.pushButton_back.setText("")
        self.pushButton_back.setObjectName("pushButton_back")
        self.label_site = QtWidgets.QLabel(self.frame_top)
        self.label_site.setGeometry(QtCore.QRect(180, 10, 111, 31))
        font = QtGui.QFont()
        font.setFamily("华光综艺_CNKI")
        font.setPointSize(16)
        self.label_site.setFont(font)
        self.label_site.setObjectName("label_site")
        self.textEdit_info = QtWidgets.QTextEdit(TeacherInfoWindow)
        self.textEdit_info.setGeometry(QtCore.QRect(0, 50, 480, 750))
        self.textEdit_info.setMinimumSize(QtCore.QSize(0, 750))
        self.textEdit_info.setObjectName("textEdit_info")

        self.retranslateUi(TeacherInfoWindow)
        QtCore.QMetaObject.connectSlotsByName(TeacherInfoWindow)

    def retranslateUi(self, TeacherInfoWindow):
        _translate = QtCore.QCoreApplication.translate
        TeacherInfoWindow.setWindowTitle(_translate("TeacherInfoWindow", "cqnu_spider"))
        self.label_site.setText(_translate("TeacherInfoWindow", "教师简介"))
import ui_rc
