# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_teachers.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TeachersWindow(object):
    def setupUi(self, TeachersWindow):
        TeachersWindow.setObjectName("TeachersWindow")
        TeachersWindow.resize(480, 800)
        TeachersWindow.setMinimumSize(QtCore.QSize(480, 800))
        TeachersWindow.setMaximumSize(QtCore.QSize(480, 800))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Icon/Images/Icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        TeachersWindow.setWindowIcon(icon)
        TeachersWindow.setStyleSheet("color: rgb(200, 200, 200);\n"
"background-color: rgb(47, 79, 79);")
        self.frame_top = QtWidgets.QFrame(TeachersWindow)
        self.frame_top.setGeometry(QtCore.QRect(0, 0, 480, 50))
        self.frame_top.setStyleSheet("background: rgb(205, 104, 57)")
        self.frame_top.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_top.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_top.setObjectName("frame_top")
        self.pushButton_back = QtWidgets.QPushButton(self.frame_top)
        self.pushButton_back.setGeometry(QtCore.QRect(430, 0, 50, 50))
        self.pushButton_back.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButton_back.setMaximumSize(QtCore.QSize(50, 50))
        self.pushButton_back.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    background-color: rgba(0,0,0,0);\n"
"    background: url(:/ui_back/Images/ui_back.png)\n"
"}\n"
"QPushButton:hover {\n"
"\n"
"    background-color: rgb(0,143,150);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgba(0,0,0,0);\n"
"}")
        self.pushButton_back.setText("")
        self.pushButton_back.setObjectName("pushButton_back")
        self.label_site = QtWidgets.QLabel(self.frame_top)
        self.label_site.setGeometry(QtCore.QRect(180, 10, 111, 31))
        font = QtGui.QFont()
        font.setFamily("华光综艺_CNKI")
        font.setPointSize(16)
        self.label_site.setFont(font)
        self.label_site.setObjectName("label_site")
        self.scrollArea = QtWidgets.QScrollArea(TeachersWindow)
        self.scrollArea.setGeometry(QtCore.QRect(0, 50, 480, 750))
        self.scrollArea.setWidgetResizable(False)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 457, 6200))
        self.scrollAreaWidgetContents.setMinimumSize(QtCore.QSize(0, 6200))
        self.scrollAreaWidgetContents.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.scrollAreaWidgetContents.setStyleSheet("")
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.widget = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget.setGeometry(QtCore.QRect(80, 60, 302, 6095))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_teacher_1 = QtWidgets.QPushButton(self.widget)
        self.pushButton_teacher_1.setMinimumSize(QtCore.QSize(300, 70))
        self.pushButton_teacher_1.setMaximumSize(QtCore.QSize(300, 70))
        font = QtGui.QFont()
        font.setFamily("华光行楷_CNKI")
        font.setPointSize(26)
        self.pushButton_teacher_1.setFont(font)
        self.pushButton_teacher_1.setStyleSheet("QPushButton {\n"
"    background-color: rgb(205, 104, 137);\n"
"    border-radius: 30px;\n"
"    border: 10px solid rgb(205, 16, 118);\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"    border: 10px solid rgb(255, 255, 0);\n"
"}")
        self.pushButton_teacher_1.setObjectName("pushButton_teacher_1")
        self.verticalLayout.addWidget(self.pushButton_teacher_1)
        self.pushButton_teacher_2 = QtWidgets.QPushButton(self.widget)
        self.pushButton_teacher_2.setMinimumSize(QtCore.QSize(300, 70))
        self.pushButton_teacher_2.setMaximumSize(QtCore.QSize(300, 70))
        font = QtGui.QFont()
        font.setFamily("华光行楷_CNKI")
        font.setPointSize(26)
        self.pushButton_teacher_2.setFont(font)
        self.pushButton_teacher_2.setStyleSheet("QPushButton {\n"
"    background-color: rgb(205, 104, 137);\n"
"    border-radius: 30px;\n"
"    border: 10px solid rgb(205, 16, 118);\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"    border: 10px solid rgb(255, 255, 0);\n"
"}")
        self.pushButton_teacher_2.setObjectName("pushButton_teacher_2")
        self.verticalLayout.addWidget(self.pushButton_teacher_2)
        self.pushButton_teacher_3 = QtWidgets.QPushButton(self.widget)
        self.pushButton_teacher_3.setMinimumSize(QtCore.QSize(300, 70))
        self.pushButton_teacher_3.setMaximumSize(QtCore.QSize(300, 70))
        font = QtGui.QFont()
        font.setFamily("华光行楷_CNKI")
        font.setPointSize(26)
        self.pushButton_teacher_3.setFont(font)
        self.pushButton_teacher_3.setStyleSheet("QPushButton {\n"
"    background-color: rgb(205, 104, 137);\n"
"    border-radius: 30px;\n"
"    border: 10px solid rgb(205, 16, 118);\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"    border: 10px solid rgb(255, 255, 0);\n"
"}")
        self.pushButton_teacher_3.setObjectName("pushButton_teacher_3")
        self.verticalLayout.addWidget(self.pushButton_teacher_3)
        self.pushButton_teacher_4 = QtWidgets.QPushButton(self.widget)
        self.pushButton_teacher_4.setMinimumSize(QtCore.QSize(300, 70))
        self.pushButton_teacher_4.setMaximumSize(QtCore.QSize(300, 70))
        font = QtGui.QFont()
        font.setFamily("华光行楷_CNKI")
        font.setPointSize(26)
        self.pushButton_teacher_4.setFont(font)
        self.pushButton_teacher_4.setStyleSheet("QPushButton {\n"
"    background-color: rgb(205, 104, 137);\n"
"    border-radius: 30px;\n"
"    border: 10px solid rgb(205, 16, 118);\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"    border: 10px solid rgb(255, 255, 0);\n"
"}")
        self.pushButton_teacher_4.setObjectName("pushButton_teacher_4")
        self.verticalLayout.addWidget(self.pushButton_teacher_4)
        self.pushButton_teacher_5 = QtWidgets.QPushButton(self.widget)
        self.pushButton_teacher_5.setMinimumSize(QtCore.QSize(300, 70))
        self.pushButton_teacher_5.setMaximumSize(QtCore.QSize(300, 70))
        font = QtGui.QFont()
        font.setFamily("华光行楷_CNKI")
        font.setPointSize(26)
        self.pushButton_teacher_5.setFont(font)
        self.pushButton_teacher_5.setStyleSheet("QPushButton {\n"
"    background-color: rgb(205, 104, 137);\n"
"    border-radius: 30px;\n"
"    border: 10px solid rgb(205, 16, 118);\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"    border: 10px solid rgb(255, 255, 0);\n"
"}")
        self.pushButton_teacher_5.setObjectName("pushButton_teacher_5")
        self.verticalLayout.addWidget(self.pushButton_teacher_5)
        self.pushButton_teacher_6 = QtWidgets.QPushButton(self.widget)
        self.pushButton_teacher_6.setMinimumSize(QtCore.QSize(300, 70))
        self.pushButton_teacher_6.setMaximumSize(QtCore.QSize(300, 70))
        font = QtGui.QFont()
        font.setFamily("华光行楷_CNKI")
        font.setPointSize(26)
        self.pushButton_teacher_6.setFont(font)
        self.pushButton_teacher_6.setStyleSheet("QPushButton {\n"
"    background-color: rgb(205, 104, 137);\n"
"    border-radius: 30px;\n"
"    border: 10px solid rgb(205, 16, 118);\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"    border: 10px solid rgb(255, 255, 0);\n"
"}")
        self.pushButton_teacher_6.setObjectName("pushButton_teacher_6")
        self.verticalLayout.addWidget(self.pushButton_teacher_6)
        self.pushButton_teacher_7 = QtWidgets.QPushButton(self.widget)
        self.pushButton_teacher_7.setMinimumSize(QtCore.QSize(300, 70))
        self.pushButton_teacher_7.setMaximumSize(QtCore.QSize(300, 70))
        font = QtGui.QFont()
        font.setFamily("华光行楷_CNKI")
        font.setPointSize(26)
        self.pushButton_teacher_7.setFont(font)
        self.pushButton_teacher_7.setStyleSheet("QPushButton {\n"
"    background-color: rgb(205, 104, 137);\n"
"    border-radius: 30px;\n"
"    border: 10px solid rgb(205, 16, 118);\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"    border: 10px solid rgb(255, 255, 0);\n"
"}")
        self.pushButton_teacher_7.setObjectName("pushButton_teacher_7")
        self.verticalLayout.addWidget(self.pushButton_teacher_7)
        self.pushButton_teacher_8 = QtWidgets.QPushButton(self.widget)
        self.pushButton_teacher_8.setMinimumSize(QtCore.QSize(300, 70))
        self.pushButton_teacher_8.setMaximumSize(QtCore.QSize(300, 70))
        font = QtGui.QFont()
        font.setFamily("华光行楷_CNKI")
        font.setPointSize(26)
        self.pushButton_teacher_8.setFont(font)
        self.pushButton_teacher_8.setStyleSheet("QPushButton {\n"
"    background-color: rgb(205, 104, 137);\n"
"    border-radius: 30px;\n"
"    border: 10px solid rgb(205, 16, 118);\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"    border: 10px solid rgb(255, 255, 0);\n"
"}")
        self.pushButton_teacher_8.setObjectName("pushButton_teacher_8")
        self.verticalLayout.addWidget(self.pushButton_teacher_8)
        self.pushButton_teacher_9 = QtWidgets.QPushButton(self.widget)
        self.pushButton_teacher_9.setMinimumSize(QtCore.QSize(300, 70))
        self.pushButton_teacher_9.setMaximumSize(QtCore.QSize(300, 70))
        font = QtGui.QFont()
        font.setFamily("华光行楷_CNKI")
        font.setPointSize(26)
        self.pushButton_teacher_9.setFont(font)
        self.pushButton_teacher_9.setStyleSheet("QPushButton {\n"
"    background-color: rgb(205, 104, 137);\n"
"    border-radius: 30px;\n"
"    border: 10px solid rgb(205, 16, 118);\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"    border: 10px solid rgb(255, 255, 0);\n"
"}")
        self.pushButton_teacher_9.setObjectName("pushButton_teacher_9")
        self.verticalLayout.addWidget(self.pushButton_teacher_9)
        self.pushButton_teacher_10 = QtWidgets.QPushButton(self.widget)
        self.pushButton_teacher_10.setMinimumSize(QtCore.QSize(300, 70))
        self.pushButton_teacher_10.setMaximumSize(QtCore.QSize(300, 70))
        font = QtGui.QFont()
        font.setFamily("华光行楷_CNKI")
        font.setPointSize(26)
        self.pushButton_teacher_10.setFont(font)
        self.pushButton_teacher_10.setStyleSheet("QPushButton {\n"
"    background-color: rgb(205, 104, 137);\n"
"    border-radius: 30px;\n"
"    border: 10px solid rgb(205, 16, 118);\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"    border: 10px solid rgb(255, 255, 0);\n"
"}")
        self.pushButton_teacher_10.setObjectName("pushButton_teacher_10")
        self.verticalLayout.addWidget(self.pushButton_teacher_10)
        self.pushButton_teacher_11 = QtWidgets.QPushButton(self.widget)
        self.pushButton_teacher_11.setMinimumSize(QtCore.QSize(300, 70))
        self.pushButton_teacher_11.setMaximumSize(QtCore.QSize(300, 70))
        font = QtGui.QFont()
        font.setFamily("华光行楷_CNKI")
        font.setPointSize(26)
        self.pushButton_teacher_11.setFont(font)
        self.pushButton_teacher_11.setStyleSheet("QPushButton {\n"
"    background-color: rgb(205, 104, 137);\n"
"    border-radius: 30px;\n"
"    border: 10px solid rgb(205, 16, 118);\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"    border: 10px solid rgb(255, 255, 0);\n"
"}")
        self.pushButton_teacher_11.setObjectName("pushButton_teacher_11")
        self.verticalLayout.addWidget(self.pushButton_teacher_11)
        self.pushButton_teacher_12 = QtWidgets.QPushButton(self.widget)
        self.pushButton_teacher_12.setMinimumSize(QtCore.QSize(300, 70))
        self.pushButton_teacher_12.setMaximumSize(QtCore.QSize(300, 70))
        font = QtGui.QFont()
        font.setFamily("华光行楷_CNKI")
        font.setPointSize(26)
        self.pushButton_teacher_12.setFont(font)
        self.pushButton_teacher_12.setStyleSheet("QPushButton {\n"
"    background-color: rgb(205, 104, 137);\n"
"    border-radius: 30px;\n"
"    border: 10px solid rgb(205, 16, 118);\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"    border: 10px solid rgb(255, 255, 0);\n"
"}")
        self.pushButton_teacher_12.setObjectName("pushButton_teacher_12")
        self.verticalLayout.addWidget(self.pushButton_teacher_12)
        self.pushButton_teacher_13 = QtWidgets.QPushButton(self.widget)
        self.pushButton_teacher_13.setMinimumSize(QtCore.QSize(300, 70))
        self.pushButton_teacher_13.setMaximumSize(QtCore.QSize(300, 70))
        font = QtGui.QFont()
        font.setFamily("华光行楷_CNKI")
        font.setPointSize(26)
        self.pushButton_teacher_13.setFont(font)
        self.pushButton_teacher_13.setStyleSheet("QPushButton {\n"
"    background-color: rgb(205, 104, 137);\n"
"    border-radius: 30px;\n"
"    border: 10px solid rgb(205, 16, 118);\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"    border: 10px solid rgb(255, 255, 0);\n"
"}")
        self.pushButton_teacher_13.setObjectName("pushButton_teacher_13")
        self.verticalLayout.addWidget(self.pushButton_teacher_13)
        self.pushButton_teacher_14 = QtWidgets.QPushButton(self.widget)
        self.pushButton_teacher_14.setMinimumSize(QtCore.QSize(300, 70))
        self.pushButton_teacher_14.setMaximumSize(QtCore.QSize(300, 70))
        font = QtGui.QFont()
        font.setFamily("华光行楷_CNKI")
        font.setPointSize(26)
        self.pushButton_teacher_14.setFont(font)
        self.pushButton_teacher_14.setStyleSheet("QPushButton {\n"
"    background-color: rgb(205, 104, 137);\n"
"    border-radius: 30px;\n"
"    border: 10px solid rgb(205, 16, 118);\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"    border: 10px solid rgb(255, 255, 0);\n"
"}")
        self.pushButton_teacher_14.setObjectName("pushButton_teacher_14")
        self.verticalLayout.addWidget(self.pushButton_teacher_14)
        self.pushButton_teacher_15 = QtWidgets.QPushButton(self.widget)
        self.pushButton_teacher_15.setMinimumSize(QtCore.QSize(300, 70))
        self.pushButton_teacher_15.setMaximumSize(QtCore.QSize(300, 70))
        font = QtGui.QFont()
        font.setFamily("华光行楷_CNKI")
        font.setPointSize(26)
        self.pushButton_teacher_15.setFont(font)
        self.pushButton_teacher_15.setStyleSheet("QPushButton {\n"
"    background-color: rgb(205, 104, 137);\n"
"    border-radius: 30px;\n"
"    border: 10px solid rgb(205, 16, 118);\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"    border: 10px solid rgb(255, 255, 0);\n"
"}")
        self.pushButton_teacher_15.setObjectName("pushButton_teacher_15")
        self.verticalLayout.addWidget(self.pushButton_teacher_15)
        self.pushButton_teacher_16 = QtWidgets.QPushButton(self.widget)
        self.pushButton_teacher_16.setMinimumSize(QtCore.QSize(300, 70))
        self.pushButton_teacher_16.setMaximumSize(QtCore.QSize(300, 70))
        font = QtGui.QFont()
        font.setFamily("华光行楷_CNKI")
        font.setPointSize(26)
        self.pushButton_teacher_16.setFont(font)
        self.pushButton_teacher_16.setStyleSheet("QPushButton {\n"
"    background-color: rgb(205, 104, 137);\n"
"    border-radius: 30px;\n"
"    border: 10px solid rgb(205, 16, 118);\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"    border: 10px solid rgb(255, 255, 0);\n"
"}")
        self.pushButton_teacher_16.setObjectName("pushButton_teacher_16")
        self.verticalLayout.addWidget(self.pushButton_teacher_16)
        self.pushButton_teacher_17 = QtWidgets.QPushButton(self.widget)
        self.pushButton_teacher_17.setMinimumSize(QtCore.QSize(300, 70))
        self.pushButton_teacher_17.setMaximumSize(QtCore.QSize(300, 70))
        font = QtGui.QFont()
        font.setFamily("华光行楷_CNKI")
        font.setPointSize(26)
        self.pushButton_teacher_17.setFont(font)
        self.pushButton_teacher_17.setStyleSheet("QPushButton {\n"
"    background-color: rgb(205, 104, 137);\n"
"    border-radius: 30px;\n"
"    border: 10px solid rgb(205, 16, 118);\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"    border: 10px solid rgb(255, 255, 0);\n"
"}")
        self.pushButton_teacher_17.setObjectName("pushButton_teacher_17")
        self.verticalLayout.addWidget(self.pushButton_teacher_17)
        self.pushButton_teacher_18 = QtWidgets.QPushButton(self.widget)
        self.pushButton_teacher_18.setMinimumSize(QtCore.QSize(300, 70))
        self.pushButton_teacher_18.setMaximumSize(QtCore.QSize(300, 70))
        font = QtGui.QFont()
        font.setFamily("华光行楷_CNKI")
        font.setPointSize(26)
        self.pushButton_teacher_18.setFont(font)
        self.pushButton_teacher_18.setStyleSheet("QPushButton {\n"
"    background-color: rgb(205, 104, 137);\n"
"    border-radius: 30px;\n"
"    border: 10px solid rgb(205, 16, 118);\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"    border: 10px solid rgb(255, 255, 0);\n"
"}")
        self.pushButton_teacher_18.setObjectName("pushButton_teacher_18")
        self.verticalLayout.addWidget(self.pushButton_teacher_18)
        self.pushButton_teacher_19 = QtWidgets.QPushButton(self.widget)
        self.pushButton_teacher_19.setMinimumSize(QtCore.QSize(300, 70))
        self.pushButton_teacher_19.setMaximumSize(QtCore.QSize(300, 70))
        font = QtGui.QFont()
        font.setFamily("华光行楷_CNKI")
        font.setPointSize(26)
        self.pushButton_teacher_19.setFont(font)
        self.pushButton_teacher_19.setStyleSheet("QPushButton {\n"
"    background-color: rgb(205, 104, 137);\n"
"    border-radius: 30px;\n"
"    border: 10px solid rgb(205, 16, 118);\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"    border: 10px solid rgb(255, 255, 0);\n"
"}")
        self.pushButton_teacher_19.setObjectName("pushButton_teacher_19")
        self.verticalLayout.addWidget(self.pushButton_teacher_19)
        self.pushButton_teacher_20 = QtWidgets.QPushButton(self.widget)
        self.pushButton_teacher_20.setMinimumSize(QtCore.QSize(300, 70))
        self.pushButton_teacher_20.setMaximumSize(QtCore.QSize(300, 70))
        font = QtGui.QFont()
        font.setFamily("华光行楷_CNKI")
        font.setPointSize(26)
        self.pushButton_teacher_20.setFont(font)
        self.pushButton_teacher_20.setStyleSheet("QPushButton {\n"
"    background-color: rgb(205, 104, 137);\n"
"    border-radius: 30px;\n"
"    border: 10px solid rgb(205, 16, 118);\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"    border: 10px solid rgb(255, 255, 0);\n"
"}")
        self.pushButton_teacher_20.setObjectName("pushButton_teacher_20")
        self.verticalLayout.addWidget(self.pushButton_teacher_20)
        self.pushButton_teacher_21 = QtWidgets.QPushButton(self.widget)
        self.pushButton_teacher_21.setMinimumSize(QtCore.QSize(300, 70))
        self.pushButton_teacher_21.setMaximumSize(QtCore.QSize(300, 70))
        font = QtGui.QFont()
        font.setFamily("华光行楷_CNKI")
        font.setPointSize(26)
        self.pushButton_teacher_21.setFont(font)
        self.pushButton_teacher_21.setStyleSheet("QPushButton {\n"
"    background-color: rgb(205, 104, 137);\n"
"    border-radius: 30px;\n"
"    border: 10px solid rgb(205, 16, 118);\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"    border: 10px solid rgb(255, 255, 0);\n"
"}")
        self.pushButton_teacher_21.setObjectName("pushButton_teacher_21")
        self.verticalLayout.addWidget(self.pushButton_teacher_21)
        self.pushButton_teacher_22 = QtWidgets.QPushButton(self.widget)
        self.pushButton_teacher_22.setMinimumSize(QtCore.QSize(300, 70))
        self.pushButton_teacher_22.setMaximumSize(QtCore.QSize(300, 70))
        font = QtGui.QFont()
        font.setFamily("华光行楷_CNKI")
        font.setPointSize(26)
        self.pushButton_teacher_22.setFont(font)
        self.pushButton_teacher_22.setStyleSheet("QPushButton {\n"
"    background-color: rgb(205, 104, 137);\n"
"    border-radius: 30px;\n"
"    border: 10px solid rgb(205, 16, 118);\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"    border: 10px solid rgb(255, 255, 0);\n"
"}")
        self.pushButton_teacher_22.setObjectName("pushButton_teacher_22")
        self.verticalLayout.addWidget(self.pushButton_teacher_22)
        self.pushButton_teacher_23 = QtWidgets.QPushButton(self.widget)
        self.pushButton_teacher_23.setMinimumSize(QtCore.QSize(300, 70))
        self.pushButton_teacher_23.setMaximumSize(QtCore.QSize(300, 70))
        font = QtGui.QFont()
        font.setFamily("华光行楷_CNKI")
        font.setPointSize(26)
        self.pushButton_teacher_23.setFont(font)
        self.pushButton_teacher_23.setStyleSheet("QPushButton {\n"
"    background-color: rgb(205, 104, 137);\n"
"    border-radius: 30px;\n"
"    border: 10px solid rgb(205, 16, 118);\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"    border: 10px solid rgb(255, 255, 0);\n"
"}")
        self.pushButton_teacher_23.setObjectName("pushButton_teacher_23")
        self.verticalLayout.addWidget(self.pushButton_teacher_23)
        self.pushButton_teacher_24 = QtWidgets.QPushButton(self.widget)
        self.pushButton_teacher_24.setMinimumSize(QtCore.QSize(300, 70))
        self.pushButton_teacher_24.setMaximumSize(QtCore.QSize(300, 70))
        font = QtGui.QFont()
        font.setFamily("华光行楷_CNKI")
        font.setPointSize(26)
        self.pushButton_teacher_24.setFont(font)
        self.pushButton_teacher_24.setStyleSheet("QPushButton {\n"
"    background-color: rgb(205, 104, 137);\n"
"    border-radius: 30px;\n"
"    border: 10px solid rgb(205, 16, 118);\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"    border: 10px solid rgb(255, 255, 0);\n"
"}")
        self.pushButton_teacher_24.setObjectName("pushButton_teacher_24")
        self.verticalLayout.addWidget(self.pushButton_teacher_24)
        self.pushButton_teacher_25 = QtWidgets.QPushButton(self.widget)
        self.pushButton_teacher_25.setMinimumSize(QtCore.QSize(300, 70))
        self.pushButton_teacher_25.setMaximumSize(QtCore.QSize(300, 70))
        font = QtGui.QFont()
        font.setFamily("华光行楷_CNKI")
        font.setPointSize(26)
        self.pushButton_teacher_25.setFont(font)
        self.pushButton_teacher_25.setStyleSheet("QPushButton {\n"
"    background-color: rgb(205, 104, 137);\n"
"    border-radius: 30px;\n"
"    border: 10px solid rgb(205, 16, 118);\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"    border: 10px solid rgb(255, 255, 0);\n"
"}")
        self.pushButton_teacher_25.setObjectName("pushButton_teacher_25")
        self.verticalLayout.addWidget(self.pushButton_teacher_25)
        self.pushButton_teacher_26 = QtWidgets.QPushButton(self.widget)
        self.pushButton_teacher_26.setMinimumSize(QtCore.QSize(300, 70))
        self.pushButton_teacher_26.setMaximumSize(QtCore.QSize(300, 70))
        font = QtGui.QFont()
        font.setFamily("华光行楷_CNKI")
        font.setPointSize(26)
        self.pushButton_teacher_26.setFont(font)
        self.pushButton_teacher_26.setStyleSheet("QPushButton {\n"
"    background-color: rgb(205, 104, 137);\n"
"    border-radius: 30px;\n"
"    border: 10px solid rgb(205, 16, 118);\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"    border: 10px solid rgb(255, 255, 0);\n"
"}")
        self.pushButton_teacher_26.setObjectName("pushButton_teacher_26")
        self.verticalLayout.addWidget(self.pushButton_teacher_26)
        self.pushButton_teacher_27 = QtWidgets.QPushButton(self.widget)
        self.pushButton_teacher_27.setMinimumSize(QtCore.QSize(300, 70))
        self.pushButton_teacher_27.setMaximumSize(QtCore.QSize(300, 70))
        font = QtGui.QFont()
        font.setFamily("华光行楷_CNKI")
        font.setPointSize(26)
        self.pushButton_teacher_27.setFont(font)
        self.pushButton_teacher_27.setStyleSheet("QPushButton {\n"
"    background-color: rgb(205, 104, 137);\n"
"    border-radius: 30px;\n"
"    border: 10px solid rgb(205, 16, 118);\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"    border: 10px solid rgb(255, 255, 0);\n"
"}")
        self.pushButton_teacher_27.setObjectName("pushButton_teacher_27")
        self.verticalLayout.addWidget(self.pushButton_teacher_27)
        self.pushButton_teacher_28 = QtWidgets.QPushButton(self.widget)
        self.pushButton_teacher_28.setMinimumSize(QtCore.QSize(300, 70))
        self.pushButton_teacher_28.setMaximumSize(QtCore.QSize(300, 70))
        font = QtGui.QFont()
        font.setFamily("华光行楷_CNKI")
        font.setPointSize(26)
        self.pushButton_teacher_28.setFont(font)
        self.pushButton_teacher_28.setStyleSheet("QPushButton {\n"
"    background-color: rgb(205, 104, 137);\n"
"    border-radius: 30px;\n"
"    border: 10px solid rgb(205, 16, 118);\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"    border: 10px solid rgb(255, 255, 0);\n"
"}")
        self.pushButton_teacher_28.setObjectName("pushButton_teacher_28")
        self.verticalLayout.addWidget(self.pushButton_teacher_28)
        self.pushButton_teacher_29 = QtWidgets.QPushButton(self.widget)
        self.pushButton_teacher_29.setMinimumSize(QtCore.QSize(300, 70))
        self.pushButton_teacher_29.setMaximumSize(QtCore.QSize(300, 70))
        font = QtGui.QFont()
        font.setFamily("华光行楷_CNKI")
        font.setPointSize(26)
        self.pushButton_teacher_29.setFont(font)
        self.pushButton_teacher_29.setStyleSheet("QPushButton {\n"
"    background-color: rgb(205, 104, 137);\n"
"    border-radius: 30px;\n"
"    border: 10px solid rgb(205, 16, 118);\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"    border: 10px solid rgb(255, 255, 0);\n"
"}")
        self.pushButton_teacher_29.setObjectName("pushButton_teacher_29")
        self.verticalLayout.addWidget(self.pushButton_teacher_29)
        self.pushButton_teacher_30 = QtWidgets.QPushButton(self.widget)
        self.pushButton_teacher_30.setMinimumSize(QtCore.QSize(300, 70))
        self.pushButton_teacher_30.setMaximumSize(QtCore.QSize(300, 70))
        font = QtGui.QFont()
        font.setFamily("华光行楷_CNKI")
        font.setPointSize(26)
        self.pushButton_teacher_30.setFont(font)
        self.pushButton_teacher_30.setStyleSheet("QPushButton {\n"
"    background-color: rgb(205, 104, 137);\n"
"    border-radius: 30px;\n"
"    border: 10px solid rgb(205, 16, 118);\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"    border: 10px solid rgb(255, 255, 0);\n"
"}")
        self.pushButton_teacher_30.setObjectName("pushButton_teacher_30")
        self.verticalLayout.addWidget(self.pushButton_teacher_30)
        self.pushButton_teacher_31 = QtWidgets.QPushButton(self.widget)
        self.pushButton_teacher_31.setMinimumSize(QtCore.QSize(300, 70))
        self.pushButton_teacher_31.setMaximumSize(QtCore.QSize(300, 70))
        font = QtGui.QFont()
        font.setFamily("华光行楷_CNKI")
        font.setPointSize(26)
        self.pushButton_teacher_31.setFont(font)
        self.pushButton_teacher_31.setStyleSheet("QPushButton {\n"
"    background-color: rgb(205, 104, 137);\n"
"    border-radius: 30px;\n"
"    border: 10px solid rgb(205, 16, 118);\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"    border: 10px solid rgb(255, 255, 0);\n"
"}")
        self.pushButton_teacher_31.setObjectName("pushButton_teacher_31")
        self.verticalLayout.addWidget(self.pushButton_teacher_31)
        self.pushButton_teacher_32 = QtWidgets.QPushButton(self.widget)
        self.pushButton_teacher_32.setMinimumSize(QtCore.QSize(300, 70))
        self.pushButton_teacher_32.setMaximumSize(QtCore.QSize(300, 70))
        font = QtGui.QFont()
        font.setFamily("华光行楷_CNKI")
        font.setPointSize(26)
        self.pushButton_teacher_32.setFont(font)
        self.pushButton_teacher_32.setStyleSheet("QPushButton {\n"
"    background-color: rgb(205, 104, 137);\n"
"    border-radius: 30px;\n"
"    border: 10px solid rgb(205, 16, 118);\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"    border: 10px solid rgb(255, 255, 0);\n"
"}")
        self.pushButton_teacher_32.setObjectName("pushButton_teacher_32")
        self.verticalLayout.addWidget(self.pushButton_teacher_32)
        self.pushButton_teacher_33 = QtWidgets.QPushButton(self.widget)
        self.pushButton_teacher_33.setMinimumSize(QtCore.QSize(300, 70))
        self.pushButton_teacher_33.setMaximumSize(QtCore.QSize(300, 70))
        font = QtGui.QFont()
        font.setFamily("华光行楷_CNKI")
        font.setPointSize(26)
        self.pushButton_teacher_33.setFont(font)
        self.pushButton_teacher_33.setStyleSheet("QPushButton {\n"
"    background-color: rgb(205, 104, 137);\n"
"    border-radius: 30px;\n"
"    border: 10px solid rgb(205, 16, 118);\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"    border: 10px solid rgb(255, 255, 0);\n"
"}")
        self.pushButton_teacher_33.setObjectName("pushButton_teacher_33")
        self.verticalLayout.addWidget(self.pushButton_teacher_33)
        self.pushButton_teacher_34 = QtWidgets.QPushButton(self.widget)
        self.pushButton_teacher_34.setMinimumSize(QtCore.QSize(300, 70))
        self.pushButton_teacher_34.setMaximumSize(QtCore.QSize(300, 70))
        font = QtGui.QFont()
        font.setFamily("华光行楷_CNKI")
        font.setPointSize(26)
        self.pushButton_teacher_34.setFont(font)
        self.pushButton_teacher_34.setStyleSheet("QPushButton {\n"
"    background-color: rgb(205, 104, 137);\n"
"    border-radius: 30px;\n"
"    border: 10px solid rgb(205, 16, 118);\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"    border: 10px solid rgb(255, 255, 0);\n"
"}")
        self.pushButton_teacher_34.setObjectName("pushButton_teacher_34")
        self.verticalLayout.addWidget(self.pushButton_teacher_34)
        self.pushButton_teacher_35 = QtWidgets.QPushButton(self.widget)
        self.pushButton_teacher_35.setMinimumSize(QtCore.QSize(300, 70))
        self.pushButton_teacher_35.setMaximumSize(QtCore.QSize(300, 70))
        font = QtGui.QFont()
        font.setFamily("华光行楷_CNKI")
        font.setPointSize(26)
        self.pushButton_teacher_35.setFont(font)
        self.pushButton_teacher_35.setStyleSheet("QPushButton {\n"
"    background-color: rgb(205, 104, 137);\n"
"    border-radius: 30px;\n"
"    border: 10px solid rgb(205, 16, 118);\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"    border: 10px solid rgb(255, 255, 0);\n"
"}")
        self.pushButton_teacher_35.setObjectName("pushButton_teacher_35")
        self.verticalLayout.addWidget(self.pushButton_teacher_35)
        self.pushButton_teacher_36 = QtWidgets.QPushButton(self.widget)
        self.pushButton_teacher_36.setMinimumSize(QtCore.QSize(300, 70))
        self.pushButton_teacher_36.setMaximumSize(QtCore.QSize(300, 70))
        font = QtGui.QFont()
        font.setFamily("华光行楷_CNKI")
        font.setPointSize(26)
        self.pushButton_teacher_36.setFont(font)
        self.pushButton_teacher_36.setStyleSheet("QPushButton {\n"
"    background-color: rgb(205, 104, 137);\n"
"    border-radius: 30px;\n"
"    border: 10px solid rgb(205, 16, 118);\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"    border: 10px solid rgb(255, 255, 0);\n"
"}")
        self.pushButton_teacher_36.setObjectName("pushButton_teacher_36")
        self.verticalLayout.addWidget(self.pushButton_teacher_36)
        self.pushButton_teacher_37 = QtWidgets.QPushButton(self.widget)
        self.pushButton_teacher_37.setMinimumSize(QtCore.QSize(300, 70))
        self.pushButton_teacher_37.setMaximumSize(QtCore.QSize(300, 70))
        font = QtGui.QFont()
        font.setFamily("华光行楷_CNKI")
        font.setPointSize(26)
        self.pushButton_teacher_37.setFont(font)
        self.pushButton_teacher_37.setStyleSheet("QPushButton {\n"
"    background-color: rgb(205, 104, 137);\n"
"    border-radius: 30px;\n"
"    border: 10px solid rgb(205, 16, 118);\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"    border: 10px solid rgb(255, 255, 0);\n"
"}")
        self.pushButton_teacher_37.setObjectName("pushButton_teacher_37")
        self.verticalLayout.addWidget(self.pushButton_teacher_37)
        self.pushButton_teacher_38 = QtWidgets.QPushButton(self.widget)
        self.pushButton_teacher_38.setMinimumSize(QtCore.QSize(300, 70))
        self.pushButton_teacher_38.setMaximumSize(QtCore.QSize(300, 70))
        font = QtGui.QFont()
        font.setFamily("华光行楷_CNKI")
        font.setPointSize(26)
        self.pushButton_teacher_38.setFont(font)
        self.pushButton_teacher_38.setStyleSheet("QPushButton {\n"
"    background-color: rgb(205, 104, 137);\n"
"    border-radius: 30px;\n"
"    border: 10px solid rgb(205, 16, 118);\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"    border: 10px solid rgb(255, 255, 0);\n"
"}")
        self.pushButton_teacher_38.setObjectName("pushButton_teacher_38")
        self.verticalLayout.addWidget(self.pushButton_teacher_38)
        self.pushButton_teacher_39 = QtWidgets.QPushButton(self.widget)
        self.pushButton_teacher_39.setMinimumSize(QtCore.QSize(300, 70))
        self.pushButton_teacher_39.setMaximumSize(QtCore.QSize(300, 70))
        font = QtGui.QFont()
        font.setFamily("华光行楷_CNKI")
        font.setPointSize(26)
        self.pushButton_teacher_39.setFont(font)
        self.pushButton_teacher_39.setStyleSheet("QPushButton {\n"
"    background-color: rgb(205, 104, 137);\n"
"    border-radius: 30px;\n"
"    border: 10px solid rgb(205, 16, 118);\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"    border: 10px solid rgb(255, 255, 0);\n"
"}")
        self.pushButton_teacher_39.setObjectName("pushButton_teacher_39")
        self.verticalLayout.addWidget(self.pushButton_teacher_39)
        self.pushButton_teacher_40 = QtWidgets.QPushButton(self.widget)
        self.pushButton_teacher_40.setMinimumSize(QtCore.QSize(300, 70))
        self.pushButton_teacher_40.setMaximumSize(QtCore.QSize(300, 70))
        font = QtGui.QFont()
        font.setFamily("华光行楷_CNKI")
        font.setPointSize(26)
        self.pushButton_teacher_40.setFont(font)
        self.pushButton_teacher_40.setStyleSheet("QPushButton {\n"
"    background-color: rgb(205, 104, 137);\n"
"    border-radius: 30px;\n"
"    border: 10px solid rgb(205, 16, 118);\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"    border: 10px solid rgb(255, 255, 0);\n"
"}")
        self.pushButton_teacher_40.setObjectName("pushButton_teacher_40")
        self.verticalLayout.addWidget(self.pushButton_teacher_40)
        self.pushButton_teacher_41 = QtWidgets.QPushButton(self.widget)
        self.pushButton_teacher_41.setMinimumSize(QtCore.QSize(300, 70))
        self.pushButton_teacher_41.setMaximumSize(QtCore.QSize(300, 70))
        font = QtGui.QFont()
        font.setFamily("华光行楷_CNKI")
        font.setPointSize(26)
        self.pushButton_teacher_41.setFont(font)
        self.pushButton_teacher_41.setStyleSheet("QPushButton {\n"
"    background-color: rgb(205, 104, 137);\n"
"    border-radius: 30px;\n"
"    border: 10px solid rgb(205, 16, 118);\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"    border: 10px solid rgb(255, 255, 0);\n"
"}")
        self.pushButton_teacher_41.setObjectName("pushButton_teacher_41")
        self.verticalLayout.addWidget(self.pushButton_teacher_41)
        self.pushButton_teacher_42 = QtWidgets.QPushButton(self.widget)
        self.pushButton_teacher_42.setMinimumSize(QtCore.QSize(300, 70))
        self.pushButton_teacher_42.setMaximumSize(QtCore.QSize(300, 70))
        font = QtGui.QFont()
        font.setFamily("华光行楷_CNKI")
        font.setPointSize(26)
        self.pushButton_teacher_42.setFont(font)
        self.pushButton_teacher_42.setStyleSheet("QPushButton {\n"
"    background-color: rgb(205, 104, 137);\n"
"    border-radius: 30px;\n"
"    border: 10px solid rgb(205, 16, 118);\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"    border: 10px solid rgb(255, 255, 0);\n"
"}")
        self.pushButton_teacher_42.setObjectName("pushButton_teacher_42")
        self.verticalLayout.addWidget(self.pushButton_teacher_42)
        self.pushButton_teacher_43 = QtWidgets.QPushButton(self.widget)
        self.pushButton_teacher_43.setMinimumSize(QtCore.QSize(300, 70))
        self.pushButton_teacher_43.setMaximumSize(QtCore.QSize(300, 70))
        font = QtGui.QFont()
        font.setFamily("华光行楷_CNKI")
        font.setPointSize(26)
        self.pushButton_teacher_43.setFont(font)
        self.pushButton_teacher_43.setStyleSheet("QPushButton {\n"
"    background-color: rgb(205, 104, 137);\n"
"    border-radius: 30px;\n"
"    border: 10px solid rgb(205, 16, 118);\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"    border: 10px solid rgb(255, 255, 0);\n"
"}")
        self.pushButton_teacher_43.setObjectName("pushButton_teacher_43")
        self.verticalLayout.addWidget(self.pushButton_teacher_43)
        self.pushButton_teacher_44 = QtWidgets.QPushButton(self.widget)
        self.pushButton_teacher_44.setMinimumSize(QtCore.QSize(300, 70))
        self.pushButton_teacher_44.setMaximumSize(QtCore.QSize(300, 70))
        font = QtGui.QFont()
        font.setFamily("华光行楷_CNKI")
        font.setPointSize(26)
        self.pushButton_teacher_44.setFont(font)
        self.pushButton_teacher_44.setStyleSheet("QPushButton {\n"
"    background-color: rgb(205, 104, 137);\n"
"    border-radius: 30px;\n"
"    border: 10px solid rgb(205, 16, 118);\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"    border: 10px solid rgb(255, 255, 0);\n"
"}")
        self.pushButton_teacher_44.setObjectName("pushButton_teacher_44")
        self.verticalLayout.addWidget(self.pushButton_teacher_44)
        self.pushButton_teacher_45 = QtWidgets.QPushButton(self.widget)
        self.pushButton_teacher_45.setMinimumSize(QtCore.QSize(300, 70))
        self.pushButton_teacher_45.setMaximumSize(QtCore.QSize(300, 70))
        font = QtGui.QFont()
        font.setFamily("华光行楷_CNKI")
        font.setPointSize(26)
        self.pushButton_teacher_45.setFont(font)
        self.pushButton_teacher_45.setStyleSheet("QPushButton {\n"
"    background-color: rgb(205, 104, 137);\n"
"    border-radius: 30px;\n"
"    border: 10px solid rgb(205, 16, 118);\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"    border: 10px solid rgb(255, 255, 0);\n"
"}")
        self.pushButton_teacher_45.setObjectName("pushButton_teacher_45")
        self.verticalLayout.addWidget(self.pushButton_teacher_45)
        self.pushButton_teacher_46 = QtWidgets.QPushButton(self.widget)
        self.pushButton_teacher_46.setMinimumSize(QtCore.QSize(300, 70))
        self.pushButton_teacher_46.setMaximumSize(QtCore.QSize(300, 70))
        font = QtGui.QFont()
        font.setFamily("华光行楷_CNKI")
        font.setPointSize(26)
        self.pushButton_teacher_46.setFont(font)
        self.pushButton_teacher_46.setStyleSheet("QPushButton {\n"
"    background-color: rgb(205, 104, 137);\n"
"    border-radius: 30px;\n"
"    border: 10px solid rgb(205, 16, 118);\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"    border: 10px solid rgb(255, 255, 0);\n"
"}")
        self.pushButton_teacher_46.setObjectName("pushButton_teacher_46")
        self.verticalLayout.addWidget(self.pushButton_teacher_46)
        self.pushButton_teacher_47 = QtWidgets.QPushButton(self.widget)
        self.pushButton_teacher_47.setMinimumSize(QtCore.QSize(300, 70))
        self.pushButton_teacher_47.setMaximumSize(QtCore.QSize(300, 70))
        font = QtGui.QFont()
        font.setFamily("华光行楷_CNKI")
        font.setPointSize(26)
        self.pushButton_teacher_47.setFont(font)
        self.pushButton_teacher_47.setStyleSheet("QPushButton {\n"
"    background-color: rgb(205, 104, 137);\n"
"    border-radius: 30px;\n"
"    border: 10px solid rgb(205, 16, 118);\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"    border: 10px solid rgb(255, 255, 0);\n"
"}")
        self.pushButton_teacher_47.setObjectName("pushButton_teacher_47")
        self.verticalLayout.addWidget(self.pushButton_teacher_47)
        self.pushButton_teacher_48 = QtWidgets.QPushButton(self.widget)
        self.pushButton_teacher_48.setMinimumSize(QtCore.QSize(300, 70))
        self.pushButton_teacher_48.setMaximumSize(QtCore.QSize(300, 70))
        font = QtGui.QFont()
        font.setFamily("华光行楷_CNKI")
        font.setPointSize(26)
        self.pushButton_teacher_48.setFont(font)
        self.pushButton_teacher_48.setStyleSheet("QPushButton {\n"
"    background-color: rgb(205, 104, 137);\n"
"    border-radius: 30px;\n"
"    border: 10px solid rgb(205, 16, 118);\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"    border: 10px solid rgb(255, 255, 0);\n"
"}")
        self.pushButton_teacher_48.setObjectName("pushButton_teacher_48")
        self.verticalLayout.addWidget(self.pushButton_teacher_48)
        self.pushButton_teacher_49 = QtWidgets.QPushButton(self.widget)
        self.pushButton_teacher_49.setMinimumSize(QtCore.QSize(300, 70))
        self.pushButton_teacher_49.setMaximumSize(QtCore.QSize(300, 70))
        font = QtGui.QFont()
        font.setFamily("华光行楷_CNKI")
        font.setPointSize(26)
        self.pushButton_teacher_49.setFont(font)
        self.pushButton_teacher_49.setStyleSheet("QPushButton {\n"
"    background-color: rgb(205, 104, 137);\n"
"    border-radius: 30px;\n"
"    border: 10px solid rgb(205, 16, 118);\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"    border: 10px solid rgb(255, 255, 0);\n"
"}")
        self.pushButton_teacher_49.setObjectName("pushButton_teacher_49")
        self.verticalLayout.addWidget(self.pushButton_teacher_49)
        self.pushButton_teacher_50 = QtWidgets.QPushButton(self.widget)
        self.pushButton_teacher_50.setMinimumSize(QtCore.QSize(300, 70))
        self.pushButton_teacher_50.setMaximumSize(QtCore.QSize(300, 70))
        font = QtGui.QFont()
        font.setFamily("华光行楷_CNKI")
        font.setPointSize(26)
        self.pushButton_teacher_50.setFont(font)
        self.pushButton_teacher_50.setStyleSheet("QPushButton {\n"
"    background-color: rgb(205, 104, 137);\n"
"    border-radius: 30px;\n"
"    border: 10px solid rgb(205, 16, 118);\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"    border: 10px solid rgb(255, 255, 0);\n"
"}")
        self.pushButton_teacher_50.setObjectName("pushButton_teacher_50")
        self.verticalLayout.addWidget(self.pushButton_teacher_50)
        self.pushButton_teacher_51 = QtWidgets.QPushButton(self.widget)
        self.pushButton_teacher_51.setMinimumSize(QtCore.QSize(300, 70))
        self.pushButton_teacher_51.setMaximumSize(QtCore.QSize(300, 70))
        font = QtGui.QFont()
        font.setFamily("华光行楷_CNKI")
        font.setPointSize(26)
        self.pushButton_teacher_51.setFont(font)
        self.pushButton_teacher_51.setStyleSheet("QPushButton {\n"
"    background-color: rgb(205, 104, 137);\n"
"    border-radius: 30px;\n"
"    border: 10px solid rgb(205, 16, 118);\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"    border: 10px solid rgb(255, 255, 0);\n"
"}")
        self.pushButton_teacher_51.setObjectName("pushButton_teacher_51")
        self.verticalLayout.addWidget(self.pushButton_teacher_51)
        self.pushButton_teacher_52 = QtWidgets.QPushButton(self.widget)
        self.pushButton_teacher_52.setMinimumSize(QtCore.QSize(300, 70))
        self.pushButton_teacher_52.setMaximumSize(QtCore.QSize(300, 70))
        font = QtGui.QFont()
        font.setFamily("华光行楷_CNKI")
        font.setPointSize(26)
        self.pushButton_teacher_52.setFont(font)
        self.pushButton_teacher_52.setStyleSheet("QPushButton {\n"
"    background-color: rgb(205, 104, 137);\n"
"    border-radius: 30px;\n"
"    border: 10px solid rgb(205, 16, 118);\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"    border: 10px solid rgb(255, 255, 0);\n"
"}")
        self.pushButton_teacher_52.setObjectName("pushButton_teacher_52")
        self.verticalLayout.addWidget(self.pushButton_teacher_52)
        self.pushButton_teacher_53 = QtWidgets.QPushButton(self.widget)
        self.pushButton_teacher_53.setMinimumSize(QtCore.QSize(300, 70))
        self.pushButton_teacher_53.setMaximumSize(QtCore.QSize(300, 70))
        font = QtGui.QFont()
        font.setFamily("华光行楷_CNKI")
        font.setPointSize(26)
        self.pushButton_teacher_53.setFont(font)
        self.pushButton_teacher_53.setStyleSheet("QPushButton {\n"
"    background-color: rgb(205, 104, 137);\n"
"    border-radius: 30px;\n"
"    border: 10px solid rgb(205, 16, 118);\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"    border: 10px solid rgb(255, 255, 0);\n"
"}")
        self.pushButton_teacher_53.setObjectName("pushButton_teacher_53")
        self.verticalLayout.addWidget(self.pushButton_teacher_53)
        self.pushButton_teacher_54 = QtWidgets.QPushButton(self.widget)
        self.pushButton_teacher_54.setMinimumSize(QtCore.QSize(300, 70))
        self.pushButton_teacher_54.setMaximumSize(QtCore.QSize(300, 70))
        font = QtGui.QFont()
        font.setFamily("华光行楷_CNKI")
        font.setPointSize(26)
        self.pushButton_teacher_54.setFont(font)
        self.pushButton_teacher_54.setStyleSheet("QPushButton {\n"
"    background-color: rgb(205, 104, 137);\n"
"    border-radius: 30px;\n"
"    border: 10px solid rgb(205, 16, 118);\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"    border: 10px solid rgb(255, 255, 0);\n"
"}")
        self.pushButton_teacher_54.setObjectName("pushButton_teacher_54")
        self.verticalLayout.addWidget(self.pushButton_teacher_54)
        self.pushButton_teacher_55 = QtWidgets.QPushButton(self.widget)
        self.pushButton_teacher_55.setMinimumSize(QtCore.QSize(300, 70))
        self.pushButton_teacher_55.setMaximumSize(QtCore.QSize(300, 70))
        font = QtGui.QFont()
        font.setFamily("华光行楷_CNKI")
        font.setPointSize(26)
        self.pushButton_teacher_55.setFont(font)
        self.pushButton_teacher_55.setStyleSheet("QPushButton {\n"
"    background-color: rgb(205, 104, 137);\n"
"    border-radius: 30px;\n"
"    border: 10px solid rgb(205, 16, 118);\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"    border: 10px solid rgb(255, 255, 0);\n"
"}")
        self.pushButton_teacher_55.setObjectName("pushButton_teacher_55")
        self.verticalLayout.addWidget(self.pushButton_teacher_55)
        self.pushButton_teacher_56 = QtWidgets.QPushButton(self.widget)
        self.pushButton_teacher_56.setMinimumSize(QtCore.QSize(300, 70))
        self.pushButton_teacher_56.setMaximumSize(QtCore.QSize(300, 70))
        font = QtGui.QFont()
        font.setFamily("华光行楷_CNKI")
        font.setPointSize(26)
        self.pushButton_teacher_56.setFont(font)
        self.pushButton_teacher_56.setStyleSheet("QPushButton {\n"
"    background-color: rgb(205, 104, 137);\n"
"    border-radius: 30px;\n"
"    border: 10px solid rgb(205, 16, 118);\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"    border: 10px solid rgb(255, 255, 0);\n"
"}")
        self.pushButton_teacher_56.setObjectName("pushButton_teacher_56")
        self.verticalLayout.addWidget(self.pushButton_teacher_56)
        self.pushButton_teacher_57 = QtWidgets.QPushButton(self.widget)
        self.pushButton_teacher_57.setMinimumSize(QtCore.QSize(300, 70))
        self.pushButton_teacher_57.setMaximumSize(QtCore.QSize(300, 70))
        font = QtGui.QFont()
        font.setFamily("华光行楷_CNKI")
        font.setPointSize(26)
        self.pushButton_teacher_57.setFont(font)
        self.pushButton_teacher_57.setStyleSheet("QPushButton {\n"
"    background-color: rgb(205, 104, 137);\n"
"    border-radius: 30px;\n"
"    border: 10px solid rgb(205, 16, 118);\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"    border: 10px solid rgb(255, 255, 0);\n"
"}")
        self.pushButton_teacher_57.setObjectName("pushButton_teacher_57")
        self.verticalLayout.addWidget(self.pushButton_teacher_57)
        self.pushButton_teacher_58 = QtWidgets.QPushButton(self.widget)
        self.pushButton_teacher_58.setMinimumSize(QtCore.QSize(300, 70))
        self.pushButton_teacher_58.setMaximumSize(QtCore.QSize(300, 70))
        font = QtGui.QFont()
        font.setFamily("华光行楷_CNKI")
        font.setPointSize(26)
        self.pushButton_teacher_58.setFont(font)
        self.pushButton_teacher_58.setStyleSheet("QPushButton {\n"
"    background-color: rgb(205, 104, 137);\n"
"    border-radius: 30px;\n"
"    border: 10px solid rgb(205, 16, 118);\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"    border: 10px solid rgb(255, 255, 0);\n"
"}")
        self.pushButton_teacher_58.setObjectName("pushButton_teacher_58")
        self.verticalLayout.addWidget(self.pushButton_teacher_58)
        self.pushButton_teacher_59 = QtWidgets.QPushButton(self.widget)
        self.pushButton_teacher_59.setMinimumSize(QtCore.QSize(300, 70))
        self.pushButton_teacher_59.setMaximumSize(QtCore.QSize(300, 70))
        font = QtGui.QFont()
        font.setFamily("华光行楷_CNKI")
        font.setPointSize(26)
        self.pushButton_teacher_59.setFont(font)
        self.pushButton_teacher_59.setStyleSheet("QPushButton {\n"
"    background-color: rgb(205, 104, 137);\n"
"    border-radius: 30px;\n"
"    border: 10px solid rgb(205, 16, 118);\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"    border: 10px solid rgb(255, 255, 0);\n"
"}")
        self.pushButton_teacher_59.setObjectName("pushButton_teacher_59")
        self.verticalLayout.addWidget(self.pushButton_teacher_59)
        self.pushButton_teacher_60 = QtWidgets.QPushButton(self.widget)
        self.pushButton_teacher_60.setMinimumSize(QtCore.QSize(300, 70))
        self.pushButton_teacher_60.setMaximumSize(QtCore.QSize(300, 70))
        font = QtGui.QFont()
        font.setFamily("华光行楷_CNKI")
        font.setPointSize(26)
        self.pushButton_teacher_60.setFont(font)
        self.pushButton_teacher_60.setStyleSheet("QPushButton {\n"
"    background-color: rgb(205, 104, 137);\n"
"    border-radius: 30px;\n"
"    border: 10px solid rgb(205, 16, 118);\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"    border: 10px solid rgb(255, 255, 0);\n"
"}")
        self.pushButton_teacher_60.setObjectName("pushButton_teacher_60")
        self.verticalLayout.addWidget(self.pushButton_teacher_60)
        self.pushButton_teacher_61 = QtWidgets.QPushButton(self.widget)
        self.pushButton_teacher_61.setMinimumSize(QtCore.QSize(300, 70))
        self.pushButton_teacher_61.setMaximumSize(QtCore.QSize(300, 70))
        font = QtGui.QFont()
        font.setFamily("华光行楷_CNKI")
        font.setPointSize(26)
        self.pushButton_teacher_61.setFont(font)
        self.pushButton_teacher_61.setStyleSheet("QPushButton {\n"
"    background-color: rgb(205, 104, 137);\n"
"    border-radius: 30px;\n"
"    border: 10px solid rgb(205, 16, 118);\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"    border: 10px solid rgb(255, 255, 0);\n"
"}")
        self.pushButton_teacher_61.setObjectName("pushButton_teacher_61")
        self.verticalLayout.addWidget(self.pushButton_teacher_61)
        self.pushButton_teacher_62 = QtWidgets.QPushButton(self.widget)
        self.pushButton_teacher_62.setMinimumSize(QtCore.QSize(300, 70))
        self.pushButton_teacher_62.setMaximumSize(QtCore.QSize(300, 70))
        font = QtGui.QFont()
        font.setFamily("华光行楷_CNKI")
        font.setPointSize(26)
        self.pushButton_teacher_62.setFont(font)
        self.pushButton_teacher_62.setStyleSheet("QPushButton {\n"
"    background-color: rgb(205, 104, 137);\n"
"    border-radius: 30px;\n"
"    border: 10px solid rgb(205, 16, 118);\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"    border: 10px solid rgb(255, 255, 0);\n"
"}")
        self.pushButton_teacher_62.setObjectName("pushButton_teacher_62")
        self.verticalLayout.addWidget(self.pushButton_teacher_62)
        self.pushButton_teacher_63 = QtWidgets.QPushButton(self.widget)
        self.pushButton_teacher_63.setMinimumSize(QtCore.QSize(300, 70))
        self.pushButton_teacher_63.setMaximumSize(QtCore.QSize(300, 70))
        font = QtGui.QFont()
        font.setFamily("华光行楷_CNKI")
        font.setPointSize(26)
        self.pushButton_teacher_63.setFont(font)
        self.pushButton_teacher_63.setStyleSheet("QPushButton {\n"
"    background-color: rgb(205, 104, 137);\n"
"    border-radius: 30px;\n"
"    border: 10px solid rgb(205, 16, 118);\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"    border: 10px solid rgb(255, 255, 0);\n"
"}")
        self.pushButton_teacher_63.setObjectName("pushButton_teacher_63")
        self.verticalLayout.addWidget(self.pushButton_teacher_63)
        self.pushButton_teacher_64 = QtWidgets.QPushButton(self.widget)
        self.pushButton_teacher_64.setMinimumSize(QtCore.QSize(300, 70))
        self.pushButton_teacher_64.setMaximumSize(QtCore.QSize(300, 70))
        font = QtGui.QFont()
        font.setFamily("华光行楷_CNKI")
        font.setPointSize(26)
        self.pushButton_teacher_64.setFont(font)
        self.pushButton_teacher_64.setStyleSheet("QPushButton {\n"
"    background-color: rgb(205, 104, 137);\n"
"    border-radius: 30px;\n"
"    border: 10px solid rgb(205, 16, 118);\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"    border: 10px solid rgb(255, 255, 0);\n"
"}")
        self.pushButton_teacher_64.setObjectName("pushButton_teacher_64")
        self.verticalLayout.addWidget(self.pushButton_teacher_64)
        self.pushButton_teacher_65 = QtWidgets.QPushButton(self.widget)
        self.pushButton_teacher_65.setMinimumSize(QtCore.QSize(300, 70))
        self.pushButton_teacher_65.setMaximumSize(QtCore.QSize(300, 70))
        font = QtGui.QFont()
        font.setFamily("华光行楷_CNKI")
        font.setPointSize(26)
        self.pushButton_teacher_65.setFont(font)
        self.pushButton_teacher_65.setStyleSheet("QPushButton {\n"
"    background-color: rgb(205, 104, 137);\n"
"    border-radius: 30px;\n"
"    border: 10px solid rgb(205, 16, 118);\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"    border: 10px solid rgb(255, 255, 0);\n"
"}")
        self.pushButton_teacher_65.setObjectName("pushButton_teacher_65")
        self.verticalLayout.addWidget(self.pushButton_teacher_65)
        self.pushButton_teacher_66 = QtWidgets.QPushButton(self.widget)
        self.pushButton_teacher_66.setMinimumSize(QtCore.QSize(300, 70))
        self.pushButton_teacher_66.setMaximumSize(QtCore.QSize(300, 70))
        font = QtGui.QFont()
        font.setFamily("华光行楷_CNKI")
        font.setPointSize(26)
        self.pushButton_teacher_66.setFont(font)
        self.pushButton_teacher_66.setStyleSheet("QPushButton {\n"
"    background-color: rgb(205, 104, 137);\n"
"    border-radius: 30px;\n"
"    border: 10px solid rgb(205, 16, 118);\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"    border: 10px solid rgb(255, 255, 0);\n"
"}")
        self.pushButton_teacher_66.setObjectName("pushButton_teacher_66")
        self.verticalLayout.addWidget(self.pushButton_teacher_66)
        self.pushButton_teacher_67 = QtWidgets.QPushButton(self.widget)
        self.pushButton_teacher_67.setMinimumSize(QtCore.QSize(300, 70))
        self.pushButton_teacher_67.setMaximumSize(QtCore.QSize(300, 70))
        font = QtGui.QFont()
        font.setFamily("华光行楷_CNKI")
        font.setPointSize(26)
        self.pushButton_teacher_67.setFont(font)
        self.pushButton_teacher_67.setStyleSheet("QPushButton {\n"
"    background-color: rgb(205, 104, 137);\n"
"    border-radius: 30px;\n"
"    border: 10px solid rgb(205, 16, 118);\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"    border: 10px solid rgb(255, 255, 0);\n"
"}")
        self.pushButton_teacher_67.setObjectName("pushButton_teacher_67")
        self.verticalLayout.addWidget(self.pushButton_teacher_67)
        self.pushButton_teacher_68 = QtWidgets.QPushButton(self.widget)
        self.pushButton_teacher_68.setMinimumSize(QtCore.QSize(300, 70))
        self.pushButton_teacher_68.setMaximumSize(QtCore.QSize(300, 70))
        font = QtGui.QFont()
        font.setFamily("华光行楷_CNKI")
        font.setPointSize(26)
        self.pushButton_teacher_68.setFont(font)
        self.pushButton_teacher_68.setStyleSheet("QPushButton {\n"
"    background-color: rgb(205, 104, 137);\n"
"    border-radius: 30px;\n"
"    border: 10px solid rgb(205, 16, 118);\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"    border: 10px solid rgb(255, 255, 0);\n"
"}")
        self.pushButton_teacher_68.setObjectName("pushButton_teacher_68")
        self.verticalLayout.addWidget(self.pushButton_teacher_68)
        self.pushButton_teacher_69 = QtWidgets.QPushButton(self.widget)
        self.pushButton_teacher_69.setMinimumSize(QtCore.QSize(300, 70))
        self.pushButton_teacher_69.setMaximumSize(QtCore.QSize(300, 70))
        font = QtGui.QFont()
        font.setFamily("华光行楷_CNKI")
        font.setPointSize(26)
        self.pushButton_teacher_69.setFont(font)
        self.pushButton_teacher_69.setStyleSheet("QPushButton {\n"
"    background-color: rgb(205, 104, 137);\n"
"    border-radius: 30px;\n"
"    border: 10px solid rgb(205, 16, 118);\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"    border: 10px solid rgb(255, 255, 0);\n"
"}")
        self.pushButton_teacher_69.setObjectName("pushButton_teacher_69")
        self.verticalLayout.addWidget(self.pushButton_teacher_69)
        self.pushButton_teacher_70 = QtWidgets.QPushButton(self.widget)
        self.pushButton_teacher_70.setMinimumSize(QtCore.QSize(300, 70))
        self.pushButton_teacher_70.setMaximumSize(QtCore.QSize(300, 70))
        font = QtGui.QFont()
        font.setFamily("华光行楷_CNKI")
        font.setPointSize(26)
        self.pushButton_teacher_70.setFont(font)
        self.pushButton_teacher_70.setStyleSheet("QPushButton {\n"
"    background-color: rgb(205, 104, 137);\n"
"    border-radius: 30px;\n"
"    border: 10px solid rgb(205, 16, 118);\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"    border: 10px solid rgb(255, 255, 0);\n"
"}")
        self.pushButton_teacher_70.setObjectName("pushButton_teacher_70")
        self.verticalLayout.addWidget(self.pushButton_teacher_70)
        self.pushButton_teacher_71 = QtWidgets.QPushButton(self.widget)
        self.pushButton_teacher_71.setMinimumSize(QtCore.QSize(300, 70))
        self.pushButton_teacher_71.setMaximumSize(QtCore.QSize(300, 70))
        font = QtGui.QFont()
        font.setFamily("华光行楷_CNKI")
        font.setPointSize(26)
        self.pushButton_teacher_71.setFont(font)
        self.pushButton_teacher_71.setStyleSheet("QPushButton {\n"
"    background-color: rgb(205, 104, 137);\n"
"    border-radius: 30px;\n"
"    border: 10px solid rgb(205, 16, 118);\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"    border: 10px solid rgb(255, 255, 0);\n"
"}")
        self.pushButton_teacher_71.setObjectName("pushButton_teacher_71")
        self.verticalLayout.addWidget(self.pushButton_teacher_71)
        self.pushButton_teacher_72 = QtWidgets.QPushButton(self.widget)
        self.pushButton_teacher_72.setMinimumSize(QtCore.QSize(300, 70))
        self.pushButton_teacher_72.setMaximumSize(QtCore.QSize(300, 70))
        font = QtGui.QFont()
        font.setFamily("华光行楷_CNKI")
        font.setPointSize(26)
        self.pushButton_teacher_72.setFont(font)
        self.pushButton_teacher_72.setStyleSheet("QPushButton {\n"
"    background-color: rgb(205, 104, 137);\n"
"    border-radius: 30px;\n"
"    border: 10px solid rgb(205, 16, 118);\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"    border: 10px solid rgb(255, 255, 0);\n"
"}")
        self.pushButton_teacher_72.setObjectName("pushButton_teacher_72")
        self.verticalLayout.addWidget(self.pushButton_teacher_72)
        self.pushButton_teacher_73 = QtWidgets.QPushButton(self.widget)
        self.pushButton_teacher_73.setMinimumSize(QtCore.QSize(300, 70))
        self.pushButton_teacher_73.setMaximumSize(QtCore.QSize(300, 70))
        font = QtGui.QFont()
        font.setFamily("华光行楷_CNKI")
        font.setPointSize(26)
        self.pushButton_teacher_73.setFont(font)
        self.pushButton_teacher_73.setStyleSheet("QPushButton {\n"
"    background-color: rgb(205, 104, 137);\n"
"    border-radius: 30px;\n"
"    border: 10px solid rgb(205, 16, 118);\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"    border: 10px solid rgb(255, 255, 0);\n"
"}")
        self.pushButton_teacher_73.setObjectName("pushButton_teacher_73")
        self.verticalLayout.addWidget(self.pushButton_teacher_73)
        self.pushButton_teacher_74 = QtWidgets.QPushButton(self.widget)
        self.pushButton_teacher_74.setMinimumSize(QtCore.QSize(300, 70))
        self.pushButton_teacher_74.setMaximumSize(QtCore.QSize(300, 70))
        font = QtGui.QFont()
        font.setFamily("华光行楷_CNKI")
        font.setPointSize(26)
        self.pushButton_teacher_74.setFont(font)
        self.pushButton_teacher_74.setStyleSheet("QPushButton {\n"
"    background-color: rgb(205, 104, 137);\n"
"    border-radius: 30px;\n"
"    border: 10px solid rgb(205, 16, 118);\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"    border: 10px solid rgb(255, 255, 0);\n"
"}")
        self.pushButton_teacher_74.setObjectName("pushButton_teacher_74")
        self.verticalLayout.addWidget(self.pushButton_teacher_74)
        self.pushButton_teacher_75 = QtWidgets.QPushButton(self.widget)
        self.pushButton_teacher_75.setMinimumSize(QtCore.QSize(300, 70))
        self.pushButton_teacher_75.setMaximumSize(QtCore.QSize(300, 70))
        font = QtGui.QFont()
        font.setFamily("华光行楷_CNKI")
        font.setPointSize(26)
        self.pushButton_teacher_75.setFont(font)
        self.pushButton_teacher_75.setStyleSheet("QPushButton {\n"
"    background-color: rgb(205, 104, 137);\n"
"    border-radius: 30px;\n"
"    border: 10px solid rgb(205, 16, 118);\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"    border: 10px solid rgb(255, 255, 0);\n"
"}")
        self.pushButton_teacher_75.setObjectName("pushButton_teacher_75")
        self.verticalLayout.addWidget(self.pushButton_teacher_75)
        self.pushButton_teacher_76 = QtWidgets.QPushButton(self.widget)
        self.pushButton_teacher_76.setMinimumSize(QtCore.QSize(300, 70))
        self.pushButton_teacher_76.setMaximumSize(QtCore.QSize(300, 70))
        font = QtGui.QFont()
        font.setFamily("华光行楷_CNKI")
        font.setPointSize(26)
        self.pushButton_teacher_76.setFont(font)
        self.pushButton_teacher_76.setStyleSheet("QPushButton {\n"
"    background-color: rgb(205, 104, 137);\n"
"    border-radius: 30px;\n"
"    border: 10px solid rgb(205, 16, 118);\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"    border: 10px solid rgb(255, 255, 0);\n"
"}")
        self.pushButton_teacher_76.setObjectName("pushButton_teacher_76")
        self.verticalLayout.addWidget(self.pushButton_teacher_76)
        self.pushButton_teacher_77 = QtWidgets.QPushButton(self.widget)
        self.pushButton_teacher_77.setMinimumSize(QtCore.QSize(300, 70))
        self.pushButton_teacher_77.setMaximumSize(QtCore.QSize(300, 70))
        font = QtGui.QFont()
        font.setFamily("华光行楷_CNKI")
        font.setPointSize(26)
        self.pushButton_teacher_77.setFont(font)
        self.pushButton_teacher_77.setStyleSheet("QPushButton {\n"
"    background-color: rgb(205, 104, 137);\n"
"    border-radius: 30px;\n"
"    border: 10px solid rgb(205, 16, 118);\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"    border: 10px solid rgb(255, 255, 0);\n"
"}")
        self.pushButton_teacher_77.setObjectName("pushButton_teacher_77")
        self.verticalLayout.addWidget(self.pushButton_teacher_77)
        self.pushButton_teacher_78 = QtWidgets.QPushButton(self.widget)
        self.pushButton_teacher_78.setMinimumSize(QtCore.QSize(300, 70))
        self.pushButton_teacher_78.setMaximumSize(QtCore.QSize(300, 70))
        font = QtGui.QFont()
        font.setFamily("华光行楷_CNKI")
        font.setPointSize(26)
        self.pushButton_teacher_78.setFont(font)
        self.pushButton_teacher_78.setStyleSheet("QPushButton {\n"
"    background-color: rgb(205, 104, 137);\n"
"    border-radius: 30px;\n"
"    border: 10px solid rgb(205, 16, 118);\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"    border: 10px solid rgb(255, 255, 0);\n"
"}")
        self.pushButton_teacher_78.setObjectName("pushButton_teacher_548")
        self.verticalLayout.addWidget(self.pushButton_teacher_78)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)

        self.retranslateUi(TeachersWindow)
        QtCore.QMetaObject.connectSlotsByName(TeachersWindow)

    def retranslateUi(self, TeachersWindow):
        _translate = QtCore.QCoreApplication.translate
        TeachersWindow.setWindowTitle(_translate("TeachersWindow", "cqnu_spider"))
        self.label_site.setText(_translate("TeachersWindow", "教师简介"))
        self.pushButton_teacher_1.setText(_translate("TeachersWindow", "曾攀"))
        self.pushButton_teacher_2.setText(_translate("TeachersWindow", "曾绍华"))
        self.pushButton_teacher_3.setText(_translate("TeachersWindow", "曾智"))
        self.pushButton_teacher_4.setText(_translate("TeachersWindow", "陈代江"))
        self.pushButton_teacher_5.setText(_translate("TeachersWindow", "陈娟娟"))
        self.pushButton_teacher_6.setText(_translate("TeachersWindow", "陈兰"))
        self.pushButton_teacher_7.setText(_translate("TeachersWindow", "陈勇"))
        self.pushButton_teacher_8.setText(_translate("TeachersWindow", "丛鑫"))
        self.pushButton_teacher_9.setText(_translate("TeachersWindow", "崔少国"))
        self.pushButton_teacher_10.setText(_translate("TeachersWindow", "邓毅"))
        self.pushButton_teacher_11.setText(_translate("TeachersWindow", "翟浩"))
        self.pushButton_teacher_12.setText(_translate("TeachersWindow", "杜兴"))
        self.pushButton_teacher_13.setText(_translate("TeachersWindow", "范京春"))
        self.pushButton_teacher_14.setText(_translate("TeachersWindow", "范永胜"))
        self.pushButton_teacher_15.setText(_translate("TeachersWindow", "冯骥"))
        self.pushButton_teacher_16.setText(_translate("TeachersWindow", "傅帆"))
        self.pushButton_teacher_17.setText(_translate("TeachersWindow", "龚伟"))
        self.pushButton_teacher_18.setText(_translate("TeachersWindow", "郝占章"))
        self.pushButton_teacher_19.setText(_translate("TeachersWindow", "何东"))
        self.pushButton_teacher_20.setText(_translate("TeachersWindow", "何丽"))
        self.pushButton_teacher_21.setText(_translate("TeachersWindow", "江军"))
        self.pushButton_teacher_22.setText(_translate("TeachersWindow", "姜扬"))
        self.pushButton_teacher_23.setText(_translate("TeachersWindow", "蒋明宇"))
        self.pushButton_teacher_24.setText(_translate("TeachersWindow", "靳蜜静"))
        self.pushButton_teacher_25.setText(_translate("TeachersWindow", "赖莉"))
        self.pushButton_teacher_26.setText(_translate("TeachersWindow", "兰晓红"))
        self.pushButton_teacher_27.setText(_translate("TeachersWindow", "雷蕾"))
        self.pushButton_teacher_28.setText(_translate("TeachersWindow", "黎天送"))
        self.pushButton_teacher_29.setText(_translate("TeachersWindow", "李光菊"))
        self.pushButton_teacher_30.setText(_translate("TeachersWindow", "李明"))
        self.pushButton_teacher_31.setText(_translate("TeachersWindow", "李明勇"))
        self.pushButton_teacher_32.setText(_translate("TeachersWindow", "李世宏"))
        self.pushButton_teacher_33.setText(_translate("TeachersWindow", "李晓虹"))
        self.pushButton_teacher_34.setText(_translate("TeachersWindow", "刘宇"))
        self.pushButton_teacher_35.setText(_translate("TeachersWindow", "楼英浩"))
        self.pushButton_teacher_36.setText(_translate("TeachersWindow", "罗凌"))
        self.pushButton_teacher_37.setText(_translate("TeachersWindow", "罗世祥"))
        self.pushButton_teacher_38.setText(_translate("TeachersWindow", "吕佳"))
        self.pushButton_teacher_39.setText(_translate("TeachersWindow", "马燕"))
        self.pushButton_teacher_40.setText(_translate("TeachersWindow", "牟小红"))
        self.pushButton_teacher_41.setText(_translate("TeachersWindow", "牟颖"))
        self.pushButton_teacher_42.setText(_translate("TeachersWindow", "牛彦敏"))
        self.pushButton_teacher_43.setText(_translate("TeachersWindow", "彭静"))
        self.pushButton_teacher_44.setText(_translate("TeachersWindow", "彭顺顺"))
        self.pushButton_teacher_45.setText(_translate("TeachersWindow", "冉瑞生"))
        self.pushButton_teacher_46.setText(_translate("TeachersWindow", "沙轩"))
        self.pushButton_teacher_47.setText(_translate("TeachersWindow", "尚晋"))
        self.pushButton_teacher_48.setText(_translate("TeachersWindow", "宋婷婷"))
        self.pushButton_teacher_49.setText(_translate("TeachersWindow", "孙苗"))
        self.pushButton_teacher_50.setText(_translate("TeachersWindow", "孙平"))
        self.pushButton_teacher_51.setText(_translate("TeachersWindow", "谭华山"))
        self.pushButton_teacher_52.setText(_translate("TeachersWindow", "唐万梅"))
        self.pushButton_teacher_53.setText(_translate("TeachersWindow", "汪平"))
        self.pushButton_teacher_54.setText(_translate("TeachersWindow", "王艳霞"))
        self.pushButton_teacher_55.setText(_translate("TeachersWindow", "魏延"))
        self.pushButton_teacher_56.setText(_translate("TeachersWindow", "文向波"))
        self.pushButton_teacher_57.setText(_translate("TeachersWindow", "先强"))
        self.pushButton_teacher_58.setText(_translate("TeachersWindow", "肖颗"))
        self.pushButton_teacher_59.setText(_translate("TeachersWindow", "徐传运"))
        self.pushButton_teacher_60.setText(_translate("TeachersWindow", "杨丹"))
        self.pushButton_teacher_61.setText(_translate("TeachersWindow", "杨德刚"))
        self.pushButton_teacher_62.setText(_translate("TeachersWindow", "杨卫明"))
        self.pushButton_teacher_63.setText(_translate("TeachersWindow", "叶青"))
        self.pushButton_teacher_64.setText(_translate("TeachersWindow", "游中胜"))
        self.pushButton_teacher_65.setText(_translate("TeachersWindow", "余磊"))
        self.pushButton_teacher_66.setText(_translate("TeachersWindow", "余萍"))
        self.pushButton_teacher_67.setText(_translate("TeachersWindow", "詹志飞"))
        self.pushButton_teacher_68.setText(_translate("TeachersWindow", "张高亮"))
        self.pushButton_teacher_69.setText(_translate("TeachersWindow", "张万里"))
        self.pushButton_teacher_70.setText(_translate("TeachersWindow", "张文峰"))
        self.pushButton_teacher_71.setText(_translate("TeachersWindow", "张杨"))
        self.pushButton_teacher_72.setText(_translate("TeachersWindow", "张珍瑜"))
        self.pushButton_teacher_73.setText(_translate("TeachersWindow", "郑玉春"))
        self.pushButton_teacher_74.setText(_translate("TeachersWindow", "钟华"))
        self.pushButton_teacher_75.setText(_translate("TeachersWindow", "周春丽"))
        self.pushButton_teacher_76.setText(_translate("TeachersWindow", "周杨"))
        self.pushButton_teacher_77.setText(_translate("TeachersWindow", "朱德利"))
        self.pushButton_teacher_78.setText(_translate("TeachersWindow", "訾玲玲"))
import ui_rc
