# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_webs.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WebsWindow(object):
    def setupUi(self, WebsWindow):
        WebsWindow.setObjectName("WebsWindow")
        WebsWindow.resize(480, 800)
        WebsWindow.setMinimumSize(QtCore.QSize(480, 800))
        WebsWindow.setMaximumSize(QtCore.QSize(480, 800))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Icon/Images/Icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        WebsWindow.setWindowIcon(icon)
        WebsWindow.setStyleSheet("color: rgb(200, 200, 200);\n"
"background-color: rgb(47, 79, 79);")
        self.frame_top = QtWidgets.QFrame(WebsWindow)
        self.frame_top.setGeometry(QtCore.QRect(0, 0, 480, 50))
        self.frame_top.setStyleSheet("background: rgb(205, 104, 57)")
        self.frame_top.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_top.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_top.setObjectName("frame_top")
        self.pushButton_back = QtWidgets.QPushButton(self.frame_top)
        self.pushButton_back.setGeometry(QtCore.QRect(430, 0, 50, 50))
        self.pushButton_back.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButton_back.setMaximumSize(QtCore.QSize(50, 50))
        self.pushButton_back.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    background-color: rgba(0,0,0,0);\n"
"    background: url(:/ui_back/Images/ui_back.png)\n"
"}\n"
"QPushButton:hover {\n"
"\n"
"    background-color: rgb(0,143,150);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgba(0,0,0,0);\n"
"}")
        self.pushButton_back.setText("")
        self.pushButton_back.setObjectName("pushButton_back")
        self.label_reserve = QtWidgets.QLabel(self.frame_top)
        self.label_reserve.setGeometry(QtCore.QRect(180, 10, 111, 31))
        font = QtGui.QFont()
        font.setFamily("华光综艺_CNKI")
        font.setPointSize(16)
        self.label_reserve.setFont(font)
        self.label_reserve.setObjectName("label_reserve")
        self.frame_manual = QtWidgets.QFrame(WebsWindow)
        self.frame_manual.setGeometry(QtCore.QRect(0, 50, 480, 30))
        self.frame_manual.setMinimumSize(QtCore.QSize(480, 30))
        self.frame_manual.setMaximumSize(QtCore.QSize(480, 30))
        self.frame_manual.setStyleSheet("background:rgb(51,51,51);")
        self.frame_manual.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_manual.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_manual.setObjectName("frame_manual")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout(self.frame_manual)
        self.horizontalLayout_20.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_20.setSpacing(0)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.label_manual = QtWidgets.QLabel(self.frame_manual)
        font = QtGui.QFont()
        font.setFamily("华光粗黑_CNKI")
        font.setPointSize(12)
        self.label_manual.setFont(font)
        self.label_manual.setObjectName("label_manual")
        self.horizontalLayout_20.addWidget(self.label_manual)
        self.frame_auto = QtWidgets.QFrame(WebsWindow)
        self.frame_auto.setGeometry(QtCore.QRect(0, 180, 480, 30))
        self.frame_auto.setMinimumSize(QtCore.QSize(480, 30))
        self.frame_auto.setMaximumSize(QtCore.QSize(480, 30))
        self.frame_auto.setStyleSheet("background:rgb(51,51,51);")
        self.frame_auto.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_auto.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_auto.setObjectName("frame_auto")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout(self.frame_auto)
        self.horizontalLayout_21.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_21.setSpacing(0)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.label_auto = QtWidgets.QLabel(self.frame_auto)
        font = QtGui.QFont()
        font.setFamily("华光粗黑_CNKI")
        font.setPointSize(12)
        self.label_auto.setFont(font)
        self.label_auto.setObjectName("label_auto")
        self.horizontalLayout_21.addWidget(self.label_auto)
        self.frame_order = QtWidgets.QFrame(WebsWindow)
        self.frame_order.setGeometry(QtCore.QRect(0, 310, 480, 30))
        self.frame_order.setMinimumSize(QtCore.QSize(480, 30))
        self.frame_order.setMaximumSize(QtCore.QSize(480, 30))
        self.frame_order.setStyleSheet("background:rgb(51,51,51);")
        self.frame_order.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_order.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_order.setObjectName("frame_order")
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout(self.frame_order)
        self.horizontalLayout_22.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_22.setSpacing(0)
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.label_order = QtWidgets.QLabel(self.frame_order)
        font = QtGui.QFont()
        font.setFamily("华光粗黑_CNKI")
        font.setPointSize(12)
        self.label_order.setFont(font)
        self.label_order.setObjectName("label_order")
        self.horizontalLayout_22.addWidget(self.label_order)
        self.frame_manual_content = QtWidgets.QFrame(WebsWindow)
        self.frame_manual_content.setGeometry(QtCore.QRect(0, 80, 480, 100))
        self.frame_manual_content.setMinimumSize(QtCore.QSize(480, 100))
        self.frame_manual_content.setMaximumSize(QtCore.QSize(480, 100))
        self.frame_manual_content.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_manual_content.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_manual_content.setObjectName("frame_manual_content")
        self.layoutWidget = QtWidgets.QWidget(self.frame_manual_content)
        self.layoutWidget.setGeometry(QtCore.QRect(80, 10, 302, 72))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_web1 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_web1.setMinimumSize(QtCore.QSize(300, 70))
        self.pushButton_web1.setMaximumSize(QtCore.QSize(300, 70))
        font = QtGui.QFont()
        font.setFamily("华光行楷_CNKI")
        font.setPointSize(26)
        self.pushButton_web1.setFont(font)
        self.pushButton_web1.setStyleSheet("QPushButton {\n"
"    background-color: rgb(205, 104, 137);\n"
"    border-radius: 30px;\n"
"    border: 10px solid rgb(205, 16, 118);\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"    border: 10px solid rgb(255, 255, 0);\n"
"}")
        self.pushButton_web1.setObjectName("pushButton_web1")
        self.gridLayout.addWidget(self.pushButton_web1, 0, 0, 1, 1)
        self.frame_auto_content = QtWidgets.QFrame(WebsWindow)
        self.frame_auto_content.setGeometry(QtCore.QRect(0, 210, 480, 100))
        self.frame_auto_content.setMinimumSize(QtCore.QSize(480, 100))
        self.frame_auto_content.setMaximumSize(QtCore.QSize(480, 100))
        self.frame_auto_content.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_auto_content.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_auto_content.setObjectName("frame_auto_content")
        self.layoutWidget1 = QtWidgets.QWidget(self.frame_auto_content)
        self.layoutWidget1.setGeometry(QtCore.QRect(80, 10, 302, 72))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButton_web2 = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_web2.setMinimumSize(QtCore.QSize(300, 70))
        self.pushButton_web2.setMaximumSize(QtCore.QSize(300, 70))
        font = QtGui.QFont()
        font.setFamily("华光行楷_CNKI")
        font.setPointSize(26)
        self.pushButton_web2.setFont(font)
        self.pushButton_web2.setStyleSheet("QPushButton {\n"
"    background-color: rgb(205, 104, 137);\n"
"    border-radius: 30px;\n"
"    border: 10px solid rgb(205, 16, 118);\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"    border: 10px solid rgb(255, 255, 0);\n"
"}")
        self.pushButton_web2.setObjectName("pushButton_web2")
        self.gridLayout_2.addWidget(self.pushButton_web2, 0, 0, 1, 1)
        self.frame_auto_content_2 = QtWidgets.QFrame(WebsWindow)
        self.frame_auto_content_2.setGeometry(QtCore.QRect(0, 340, 480, 100))
        self.frame_auto_content_2.setMinimumSize(QtCore.QSize(480, 100))
        self.frame_auto_content_2.setMaximumSize(QtCore.QSize(480, 100))
        self.frame_auto_content_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_auto_content_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_auto_content_2.setObjectName("frame_auto_content_2")
        self.layoutWidget_2 = QtWidgets.QWidget(self.frame_auto_content_2)
        self.layoutWidget_2.setGeometry(QtCore.QRect(80, 10, 302, 72))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.layoutWidget_2)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.pushButton_web3 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton_web3.setMinimumSize(QtCore.QSize(300, 70))
        self.pushButton_web3.setMaximumSize(QtCore.QSize(300, 70))
        font = QtGui.QFont()
        font.setFamily("华光行楷_CNKI")
        font.setPointSize(26)
        self.pushButton_web3.setFont(font)
        self.pushButton_web3.setStyleSheet("QPushButton {\n"
"    background-color: rgb(205, 104, 137);\n"
"    border-radius: 30px;\n"
"    border: 10px solid rgb(205, 16, 118);\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"    border: 10px solid rgb(255, 255, 0);\n"
"}")
        self.pushButton_web3.setObjectName("pushButton_web3")
        self.gridLayout_4.addWidget(self.pushButton_web3, 0, 0, 1, 1)
        self.frame_order_2 = QtWidgets.QFrame(WebsWindow)
        self.frame_order_2.setGeometry(QtCore.QRect(0, 440, 480, 30))
        self.frame_order_2.setMinimumSize(QtCore.QSize(480, 30))
        self.frame_order_2.setMaximumSize(QtCore.QSize(480, 30))
        self.frame_order_2.setStyleSheet("background:rgb(51,51,51);")
        self.frame_order_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_order_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_order_2.setObjectName("frame_order_2")
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout(self.frame_order_2)
        self.horizontalLayout_23.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_23.setSpacing(0)
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.label_order_2 = QtWidgets.QLabel(self.frame_order_2)
        font = QtGui.QFont()
        font.setFamily("华光粗黑_CNKI")
        font.setPointSize(12)
        self.label_order_2.setFont(font)
        self.label_order_2.setObjectName("label_order_2")
        self.horizontalLayout_23.addWidget(self.label_order_2)
        self.frame_auto_content_3 = QtWidgets.QFrame(WebsWindow)
        self.frame_auto_content_3.setGeometry(QtCore.QRect(0, 470, 480, 100))
        self.frame_auto_content_3.setMinimumSize(QtCore.QSize(480, 100))
        self.frame_auto_content_3.setMaximumSize(QtCore.QSize(480, 100))
        self.frame_auto_content_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_auto_content_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_auto_content_3.setObjectName("frame_auto_content_3")
        self.layoutWidget_3 = QtWidgets.QWidget(self.frame_auto_content_3)
        self.layoutWidget_3.setGeometry(QtCore.QRect(80, 10, 302, 72))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.layoutWidget_3)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.pushButton_web4 = QtWidgets.QPushButton(self.layoutWidget_3)
        self.pushButton_web4.setMinimumSize(QtCore.QSize(300, 70))
        self.pushButton_web4.setMaximumSize(QtCore.QSize(300, 70))
        font = QtGui.QFont()
        font.setFamily("华光行楷_CNKI")
        font.setPointSize(26)
        self.pushButton_web4.setFont(font)
        self.pushButton_web4.setStyleSheet("QPushButton {\n"
"    background-color: rgb(205, 104, 137);\n"
"    border-radius: 30px;\n"
"    border: 10px solid rgb(205, 16, 118);\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"    border: 10px solid rgb(255, 255, 0);\n"
"}")
        self.pushButton_web4.setObjectName("pushButton_web4")
        self.gridLayout_5.addWidget(self.pushButton_web4, 0, 0, 1, 1)
        self.frame_auto_content_4 = QtWidgets.QFrame(WebsWindow)
        self.frame_auto_content_4.setGeometry(QtCore.QRect(0, 600, 480, 100))
        self.frame_auto_content_4.setMinimumSize(QtCore.QSize(480, 100))
        self.frame_auto_content_4.setMaximumSize(QtCore.QSize(480, 100))
        self.frame_auto_content_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_auto_content_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_auto_content_4.setObjectName("frame_auto_content_4")
        self.layoutWidget_4 = QtWidgets.QWidget(self.frame_auto_content_4)
        self.layoutWidget_4.setGeometry(QtCore.QRect(80, 10, 302, 72))
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.layoutWidget_4)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.pushButton_web5 = QtWidgets.QPushButton(self.layoutWidget_4)
        self.pushButton_web5.setMinimumSize(QtCore.QSize(300, 70))
        self.pushButton_web5.setMaximumSize(QtCore.QSize(300, 70))
        font = QtGui.QFont()
        font.setFamily("华光行楷_CNKI")
        font.setPointSize(26)
        self.pushButton_web5.setFont(font)
        self.pushButton_web5.setStyleSheet("QPushButton {\n"
"    background-color: rgb(205, 104, 137);\n"
"    border-radius: 30px;\n"
"    border: 10px solid rgb(205, 16, 118);\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"    border: 10px solid rgb(255, 255, 0);\n"
"}")
        self.pushButton_web5.setObjectName("pushButton_web5")
        self.gridLayout_6.addWidget(self.pushButton_web5, 0, 0, 1, 1)
        self.frame_order_3 = QtWidgets.QFrame(WebsWindow)
        self.frame_order_3.setGeometry(QtCore.QRect(0, 570, 480, 30))
        self.frame_order_3.setMinimumSize(QtCore.QSize(480, 30))
        self.frame_order_3.setMaximumSize(QtCore.QSize(480, 30))
        self.frame_order_3.setStyleSheet("background:rgb(51,51,51);")
        self.frame_order_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_order_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_order_3.setObjectName("frame_order_3")
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout(self.frame_order_3)
        self.horizontalLayout_24.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_24.setSpacing(0)
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.label_order_3 = QtWidgets.QLabel(self.frame_order_3)
        font = QtGui.QFont()
        font.setFamily("华光粗黑_CNKI")
        font.setPointSize(12)
        self.label_order_3.setFont(font)
        self.label_order_3.setObjectName("label_order_3")
        self.horizontalLayout_24.addWidget(self.label_order_3)

        self.retranslateUi(WebsWindow)
        QtCore.QMetaObject.connectSlotsByName(WebsWindow)

    def retranslateUi(self, WebsWindow):
        _translate = QtCore.QCoreApplication.translate
        WebsWindow.setWindowTitle(_translate("WebsWindow", "cqnu_spider"))
        self.label_reserve.setText(_translate("WebsWindow", "考研网站"))
        self.label_manual.setText(_translate("WebsWindow", "    专业目录查询、院校专业报考政策："))
        self.label_auto.setText(_translate("WebsWindow", "    分享以往的考研信息和考研经验："))
        self.label_order.setText(_translate("WebsWindow", "    研究生招生简章,考研大纲解析,考研报名攻略："))
        self.pushButton_web1.setText(_translate("WebsWindow", "研招网"))
        self.pushButton_web2.setText(_translate("WebsWindow", "考研论坛"))
        self.pushButton_web3.setText(_translate("WebsWindow", "中国考研网"))
        self.label_order_2.setText(_translate("WebsWindow", "    参考书目、招生计划、报录比查询："))
        self.pushButton_web4.setText(_translate("WebsWindow", "中国教育在线"))
        self.pushButton_web5.setText(_translate("WebsWindow", "谷粉学术"))
        self.label_order_3.setText(_translate("WebsWindow", "    论文查询："))
import ui_rc
